package generates

import (
	"fmt"
	"os"
	"regexp"
	"strings"
	"text/template"
	"time"
)

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}

package messages

import (
	"bytes"
	"fmt"
)

type {{ .Name }} struct {
	PacketId uint32
}

var {{ .Name }}_ = &{{ .Name }}{PacketId: {{ .Id }}}

func Get{{ .NameCapFirst }}NOA() *{{ .Name }} {
	return {{ .Name }}_
}

func ({{.FistLetter}} *{{.Name}}) Serialize(buff *bytes.Buffer) {

}

func ({{.FistLetter}} *{{.Name}}) Deserialize(reader *bytes.Reader) {

}

func ({{.FistLetter}} *{{.Name}}) GetPacketId() uint32 {
	return {{ .FistLetter }}.PacketId
}

func ({{.FistLetter}} *{{.Name}}) String() string {
	return fmt.Sprintf("packetId: %d\n", {{ .FistLetter }}.PacketId)
}
`))

var packageIDSTemplate = template.Must(template.New("").Parse(`// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}

package messages

const (
	{{ .constBefore }}
	{{ .NameCapFirst }} = {{ .Id }}}
)
`))

func GenerateMessage(Name string, packetId uint32) {
	f, err := os.Create(fmt.Sprintf("./messages/%s.go", Name))
	f2, err := os.Create("./messages/IDS.go")

	constIDS, _ := os.ReadFile("./messages/IDS.go")

	constIDString := string(constIDS)
	var rgx = regexp.MustCompile(`^[^(]+([^)])+.*$`)
	rs := rgx.FindStringSubmatch(constIDString)

	if err != nil {
		panic(err)
	}

	defer func(f *os.File) {
		err := f.Close()
		if err != nil {
			panic(err)
		}
	}(f)

	err = packageIDSTemplate.Execute(f2, struct {
		Timestamp    time.Time
		NameCapFirst string
		Id           uint32
		constBefore  string
	}{
		Timestamp:    time.Now(),
		NameCapFirst: strings.Title(Name),
		Id:           packetId,
		constBefore:  rs[1],
	})
	if err != nil {
		panic(err)
	}

	err = packageTemplate.Execute(f, struct {
		Timestamp    time.Time
		NameCapFirst string
		Name         string
		Id           uint32
		FistLetter   string
	}{
		Timestamp:    time.Now(),
		Name:         Name,
		NameCapFirst: strings.Title(Name),
		FistLetter:   string((Name)[0]),
	})
	if err != nil {
		panic(err)
	}
}
