// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 12:33:42.0186556 +0200 CEST m=+40.061189901

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type AbstractFightTeamInformations struct {
	PacketId   uint32
	teamId     byte
	leaderId   float64
	teamSide   byte
	teamTypeId byte
	nbWaves    byte
}

var AbstractFightTeamInformationsMap = make(map[uint]*AbstractFightTeamInformations)

func (Ab *AbstractFightTeamInformations) GetNOA(instance uint) Message {
	AbstractFightTeamInformations_, ok := AbstractFightTeamInformationsMap[instance]

	if ok {
		return AbstractFightTeamInformations_
	}

	AbstractFightTeamInformationsMap[instance] = &AbstractFightTeamInformations{PacketId: AbstractFightTeamInformationsID}
	return AbstractFightTeamInformationsMap[instance]
}

func (Ab *AbstractFightTeamInformations) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, Ab.teamId)
	_ = binary.Write(buff, binary.BigEndian, Ab.leaderId)
	_ = binary.Write(buff, binary.BigEndian, Ab.teamSide)
	_ = binary.Write(buff, binary.BigEndian, Ab.teamTypeId)
	_ = binary.Write(buff, binary.BigEndian, Ab.nbWaves)
}

func (Ab *AbstractFightTeamInformations) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &Ab.teamId)
	_ = binary.Read(reader, binary.BigEndian, &Ab.leaderId)
	_ = binary.Read(reader, binary.BigEndian, &Ab.teamSide)
	_ = binary.Read(reader, binary.BigEndian, &Ab.teamTypeId)
	_ = binary.Read(reader, binary.BigEndian, &Ab.nbWaves)
}

func (Ab *AbstractFightTeamInformations) GetPacketId() uint32 {
	return Ab.PacketId
}

func (Ab *AbstractFightTeamInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", Ab.PacketId)
}
