// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 08:07:53.9266017 +0200 CEST m=+0.021301901

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type accountTagInformation struct {
	PacketId  uint32
	nickname  []byte
	tagNumber []byte
}

var accountTagInformationMap = make(map[uint]*accountTagInformation)

func GetAccountTagInformationNOA(instance uint) *accountTagInformation {
	accountTagInformation_, ok := accountTagInformationMap[instance]

	if ok {
		return accountTagInformation_
	}

	accountTagInformationMap[instance] = &accountTagInformation{PacketId: AccountTagInformationID}
	return accountTagInformationMap[instance]
}

func (a *accountTagInformation) Serialize(buff *bytes.Buffer) {
	utils.WriteUTF(buff, a.nickname)
	utils.WriteUTF(buff, a.tagNumber)
}

func (a *accountTagInformation) Deserialize(reader *bytes.Reader) {
	a.nickname = utils.ReadUTF(reader)
	a.tagNumber = utils.ReadUTF(reader)
}

func (a *accountTagInformation) GetPacketId() uint32 {
	return a.PacketId
}

func (a *accountTagInformation) String() string {
	return fmt.Sprintf("packetId: %d\n", a.PacketId)
}
