// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 15:10:06.1626901 +0200 CEST m=+125.906987601

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type accountHouseInformations struct {
	PacketId          uint32
	houseInformations *houseInformations
	item              *item
	worldX            uint16
	worldY            uint16
	mapId             float64
	subAreaId         int32
}

var accountHouseInformationsMap = make(map[uint]*accountHouseInformations)

func (ac *accountHouseInformations) GetNOA(instance uint) Message {
	accountHouseInformations_, ok := accountHouseInformationsMap[instance]

	if ok {
		return accountHouseInformations_
	}

	accountHouseInformationsMap[instance] = &accountHouseInformations{PacketId: AccountHouseInformationsID}
	return accountHouseInformationsMap[instance]
}

func (ac *accountHouseInformations) Serialize(buff *bytes.Buffer) {
	ac.houseInformations.Serialize(buff)
	ac.item.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, ac.worldX)
	_ = binary.Write(buff, binary.BigEndian, ac.worldY)
	_ = binary.Write(buff, binary.BigEndian, ac.mapId)
	utils.WriteVarInt16(buff, ac.subAreaId)
}

func (ac *accountHouseInformations) Deserialize(reader *bytes.Reader) {
	ac.houseInformations = new(houseInformations)
	ac.houseInformations.Deserialize(reader)
	ac.item = new(item)
	ac.item.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &ac.worldX)
	_ = binary.Read(reader, binary.BigEndian, &ac.worldY)
	_ = binary.Read(reader, binary.BigEndian, &ac.mapId)
	ac.subAreaId = utils.ReadVarInt16(reader)
}

func (ac *accountHouseInformations) GetPacketId() uint32 {
	return ac.PacketId
}

func (ac *accountHouseInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", ac.PacketId)
}
