// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 23:09:04.2588962 +0200 CEST m=+57.052456901

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type acquaintanceOnlineInformation struct {
	PacketId                 uint32
	acquaintanceInformation0 *acquaintanceInformation
	playerId                 float64
	playerName               []byte
	moodSmileyId             int32
	item4                    *item
}

var acquaintanceOnlineInformationMap = make(map[uint]*acquaintanceOnlineInformation)

func (ac *acquaintanceOnlineInformation) GetNOA(instance uint) Message {
	acquaintanceOnlineInformation_, ok := acquaintanceOnlineInformationMap[instance]

	if ok {
		return acquaintanceOnlineInformation_
	}

	acquaintanceOnlineInformationMap[instance] = &acquaintanceOnlineInformation{PacketId: AcquaintanceOnlineInformationID}
	return acquaintanceOnlineInformationMap[instance]
}

func (ac *acquaintanceOnlineInformation) Serialize(buff *bytes.Buffer) {
	ac.acquaintanceInformation0.Serialize(buff)
	utils.WriteVarInt64(buff, ac.playerId)
	utils.WriteUTF(buff, ac.playerName)
	utils.WriteVarInt16(buff, ac.moodSmileyId)
	ac.item4.Serialize(buff)
}

func (ac *acquaintanceOnlineInformation) Deserialize(reader *bytes.Reader) {
	ac.acquaintanceInformation0 = new(acquaintanceInformation)
	ac.acquaintanceInformation0.Deserialize(reader)
	ac.playerId = float64(utils.ReadVarInt64(reader))
	ac.playerName = utils.ReadUTF(reader)
	ac.moodSmileyId = utils.ReadVarInt16(reader)
	ac.item4 = new(item)
	ac.item4.Deserialize(reader)
}

func (ac *acquaintanceOnlineInformation) GetPacketId() uint32 {
	return ac.PacketId
}

func (ac *acquaintanceOnlineInformation) String() string {
	return fmt.Sprintf("packetId: %d\n", ac.PacketId)
}
