// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 23:05:11.1305172 +0200 CEST m=+16.268966101

package messages

import (
	"bytes"
	"fmt"
)

type acquaintancesList struct {
	PacketId     uint32
	itemWrapper0 *itemWrapper
}

var acquaintancesListMap = make(map[uint]*acquaintancesList)

func (ac *acquaintancesList) GetNOA(instance uint) Message {
	acquaintancesList_, ok := acquaintancesListMap[instance]

	if ok {
		return acquaintancesList_
	}

	acquaintancesListMap[instance] = &acquaintancesList{PacketId: AcquaintancesListID}
	return acquaintancesListMap[instance]
}

func (ac *acquaintancesList) Serialize(buff *bytes.Buffer) {
	ac.itemWrapper0.Serialize(buff)
}

func (ac *acquaintancesList) Deserialize(reader *bytes.Reader) {
	ac.itemWrapper0 = new(itemWrapper)
	ac.itemWrapper0.Deserialize(reader)
}

func (ac *acquaintancesList) GetPacketId() uint32 {
	return ac.PacketId
}

func (ac *acquaintancesList) String() string {
	return fmt.Sprintf("packetId: %d\n", ac.PacketId)
}
