// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 22:02:19.3282505 +0200 CEST m=+0.565807601

package messages

import (
	"bytes"
	"fmt"
)

type acquaintancesGetList struct {
	PacketId uint32
}

var acquaintancesGetListMap = make(map[uint]*acquaintancesGetList)

func (ac *acquaintancesGetList) GetNOA(instance uint) Message {
	acquaintancesGetList_, ok := acquaintancesGetListMap[instance]

	if ok {
		return acquaintancesGetList_
	}

	acquaintancesGetListMap[instance] = &acquaintancesGetList{PacketId: AcquaintancesGetListID}
	return acquaintancesGetListMap[instance]
}

func (ac *acquaintancesGetList) Serialize(buff *bytes.Buffer) {
}

func (ac *acquaintancesGetList) Deserialize(reader *bytes.Reader) {
}

func (ac *acquaintancesGetList) GetPacketId() uint32 {
	return ac.PacketId
}

func (ac *acquaintancesGetList) String() string {
	return fmt.Sprintf("packetId: %d\n", ac.PacketId)
}
