// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 09:27:15.2095671 +0200 CEST m=+117.563149101

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type allianceInsiderPrismInformation struct {
	PacketId                              uint32
	prismInformation                      *prismInformation
	lastTimeSlotModificationDate          int32
	lastTimeSlotModificationAuthorGuildId int32
	lastTimeSlotModificationAuthorId      float64
	lastTimeSlotModificationAuthorName    []byte
	objectItem                            []*objectItem
}

var allianceInsiderPrismInformationMap = make(map[uint]*allianceInsiderPrismInformation)

func GetAllianceInsiderPrismInformationNOA(instance uint) *allianceInsiderPrismInformation {
	allianceInsiderPrismInformation_, ok := allianceInsiderPrismInformationMap[instance]

	if ok {
		return allianceInsiderPrismInformation_
	}

	allianceInsiderPrismInformationMap[instance] = &allianceInsiderPrismInformation{PacketId: AllianceInsiderPrismInformationID}
	return allianceInsiderPrismInformationMap[instance]
}

func (al *allianceInsiderPrismInformation) Serialize(buff *bytes.Buffer) {
	al.prismInformation.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, al.lastTimeSlotModificationDate)
	utils.WriteVarInt32(buff, al.lastTimeSlotModificationAuthorGuildId)
	utils.WriteVarInt64(buff, al.lastTimeSlotModificationAuthorId)
	utils.WriteUTF(buff, al.lastTimeSlotModificationAuthorName)
	_ = binary.Write(buff, binary.BigEndian, uint16(len(al.objectItem)))
	for i := 0; i < len(al.objectItem); i++ {
		al.objectItem[i].Serialize(buff)
	}
}

func (al *allianceInsiderPrismInformation) Deserialize(reader *bytes.Reader) {
	al.prismInformation = new(prismInformation)
	al.prismInformation.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &al.lastTimeSlotModificationDate)
	al.lastTimeSlotModificationAuthorGuildId = utils.ReadVarInt32(reader)
	al.lastTimeSlotModificationAuthorId = float64(utils.ReadVarInt64(reader))
	al.lastTimeSlotModificationAuthorName = utils.ReadUTF(reader)
	var len5_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len5_)
	al.objectItem = nil
	for i := 0; i < int(len5_); i++ {
		aMessage5 := new(objectItem)
		aMessage5.Deserialize(reader)
		al.objectItem = append(al.objectItem, aMessage5)
	}
}

func (al *allianceInsiderPrismInformation) GetPacketId() uint32 {
	return al.PacketId
}

func (al *allianceInsiderPrismInformation) String() string {
	return fmt.Sprintf("packetId: %d\n", al.PacketId)
}
