// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-25 13:31:44.2855433 +0200 CEST m=+0.003124301

package messages

import (
	"GoDofus/managers"
	"GoDofus/utils"
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"fmt"
)

type authenticationTicket struct {
	PacketId uint32
	instance uint
}

var authenticationTicketMap = make(map[uint]*authenticationTicket)

func (a *authenticationTicket) GetNOA(instance uint) Message {
	authenticationTicket_, ok := authenticationTicketMap[instance]

	if ok {
		return authenticationTicket_
	}

	authenticationTicketMap[instance] = &authenticationTicket{PacketId: AuthenticationTicketID, instance: instance}
	return authenticationTicketMap[instance]
}

func (a *authenticationTicket) Serialize(buff *bytes.Buffer) {
	idManager := managers.GetAuthentificationManager(a.instance)
	ticket := Types_[int(SelectedServerDataExtendedID)].GetNOA(a.instance).(*SelectedServerDataExtended).SSD.ticket[:]
	aesKey := idManager.AESKey[:]

	block, err := aes.NewCipher(aesKey)
	if err != nil {
		panic(err)
	}

	if len(ticket) < aes.BlockSize {
		panic("ciphertext too short")
	}
	iv := aesKey[:aes.BlockSize]

	if len(ticket)%aes.BlockSize != 0 {
		panic("ciphertext is not a multiple of the block size")
	}

	mode := cipher.NewCBCDecrypter(block, iv)
	mode.CryptBlocks(ticket, ticket)

	utils.WriteUTF(buff, idManager.Lang)
	utils.WriteUTF(buff, ticket)
}

func (a *authenticationTicket) Deserialize(reader *bytes.Reader) {

}

func (a *authenticationTicket) GetPacketId() uint32 {
	return a.PacketId
}

func (a *authenticationTicket) String() string {
	return fmt.Sprintf("packetId: %d\n", a.PacketId)
}
