// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-27 13:46:30.6818649 +0200 CEST m=+0.003110301

package messages

import (
	"bytes"
	"fmt"
)

type authenticationTicketAccepted struct {
	PacketId uint32
}

var authenticationTicketAcceptedMap = make(map[uint]*authenticationTicketAccepted)

func (a *authenticationTicketAccepted) GetNOA(instance uint) Message {
	authenticationTicketAccepted_, ok := authenticationTicketAcceptedMap[instance]

	if ok {
		return authenticationTicketAccepted_
	}

	authenticationTicketAcceptedMap[instance] = &authenticationTicketAccepted{PacketId: AuthenticationTicketAcceptedID}
	return authenticationTicketAcceptedMap[instance]
}

func (a *authenticationTicketAccepted) Serialize(buff *bytes.Buffer) {

}

func (a *authenticationTicketAccepted) Deserialize(reader *bytes.Reader) {

}

func (a *authenticationTicketAccepted) GetPacketId() uint32 {
	return a.PacketId
}

func (a *authenticationTicketAccepted) String() string {
	return fmt.Sprintf("packetId: %d\n", a.PacketId)
}
