// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 09:12:05.1460302 +0200 CEST m=+10.884200201

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type basicNamedAllianceInformation struct {
	PacketId                  uint32
	basicAllianceInformations *basicAllianceInformations
	allianceName              []byte
}

var basicNamedAllianceInformationMap = make(map[uint]*basicNamedAllianceInformation)

func (ba *basicNamedAllianceInformation) GetNOA(instance uint) Message {
	basicNamedAllianceInformation_, ok := basicNamedAllianceInformationMap[instance]

	if ok {
		return basicNamedAllianceInformation_
	}

	basicNamedAllianceInformationMap[instance] = &basicNamedAllianceInformation{PacketId: BasicNamedAllianceInformationID}
	return basicNamedAllianceInformationMap[instance]
}

func (ba *basicNamedAllianceInformation) Serialize(buff *bytes.Buffer) {
	ba.basicAllianceInformations.Serialize(buff)
	utils.WriteUTF(buff, ba.allianceName)
}

func (ba *basicNamedAllianceInformation) Deserialize(reader *bytes.Reader) {
	ba.basicAllianceInformations = new(basicAllianceInformations)
	ba.basicAllianceInformations.Deserialize(reader)
	ba.allianceName = utils.ReadUTF(reader)
}

func (ba *basicNamedAllianceInformation) GetPacketId() uint32 {
	return ba.PacketId
}

func (ba *basicNamedAllianceInformation) String() string {
	return fmt.Sprintf("packetId: %d\n", ba.PacketId)
}
