// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 22:04:43.199377 +0200 CEST m=+0.797457101

package messages

import (
	"bytes"
	"fmt"
)

type basicNoOperation struct {
	PacketId uint32
}

var basicNoOperationMap = make(map[uint]*basicNoOperation)

func (ba *basicNoOperation) GetNOA(instance uint) Message {
	basicNoOperation_, ok := basicNoOperationMap[instance]

	if ok {
		return basicNoOperation_
	}

	basicNoOperationMap[instance] = &basicNoOperation{PacketId: BasicNoOperationID}
	return basicNoOperationMap[instance]
}

func (ba *basicNoOperation) Serialize(buff *bytes.Buffer) {
}

func (ba *basicNoOperation) Deserialize(reader *bytes.Reader) {
}

func (ba *basicNoOperation) GetPacketId() uint32 {
	return ba.PacketId
}

func (ba *basicNoOperation) String() string {
	return fmt.Sprintf("packetId: %d\n", ba.PacketId)
}
