// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 09:10:10.8581444 +0200 CEST m=+22.116780801

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type basicAllianceInformations struct {
	PacketId    uint32
	allianceId  int32
	allianceTag []byte
}

var basicAllianceInformationsMap = make(map[uint]*basicAllianceInformations)

func (ba *basicAllianceInformations) GetNOA(instance uint) Message {
	basicAllianceInformations_, ok := basicAllianceInformationsMap[instance]

	if ok {
		return basicAllianceInformations_
	}

	basicAllianceInformationsMap[instance] = &basicAllianceInformations{PacketId: BasicAllianceInformationsID}
	return basicAllianceInformationsMap[instance]
}

func (ba *basicAllianceInformations) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt32(buff, ba.allianceId)
	utils.WriteUTF(buff, ba.allianceTag)
}

func (ba *basicAllianceInformations) Deserialize(reader *bytes.Reader) {
	ba.allianceId = utils.ReadVarInt32(reader)
	ba.allianceTag = utils.ReadUTF(reader)
}

func (ba *basicAllianceInformations) GetPacketId() uint32 {
	return ba.PacketId
}

func (ba *basicAllianceInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", ba.PacketId)
}
