// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-28 20:07:39.0122938 +0200 CEST m=+0.023438401

package messages

import (
	"bytes"
	"fmt"
)

type basicCharactersList struct {
	PacketId uint32
	iW       *itemWrapper
}

var basicCharactersListMap = make(map[uint]*basicCharactersList)

func (b *basicCharactersList) GetNOA(instance uint) Message {
	basicCharactersList_, ok := basicCharactersListMap[instance]

	if ok {
		return basicCharactersList_
	}

	basicCharactersListMap[instance] = &basicCharactersList{PacketId: BasicCharactersListID}
	return basicCharactersListMap[instance]
}

func (b *basicCharactersList) Serialize(buff *bytes.Buffer) {
	b.iW.Serialize(buff)
}

func (b *basicCharactersList) Deserialize(reader *bytes.Reader) {
	b.iW = new(itemWrapper)
	b.iW.Deserialize(reader)
}

func (b *basicCharactersList) GetPacketId() uint32 {
	return b.PacketId
}

func (b *basicCharactersList) String() string {
	return fmt.Sprintf("packetId: %d\n", b.PacketId)
}
