// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 08:39:53.7215403 +0200 CEST m=+0.021221901

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type characterSelection struct {
	PacketId uint32
	id       float64
}

var characterSelectionMap = make(map[uint]*characterSelection)

func (c *characterSelection) GetNOA(instance uint) Message {
	characterSelection_, ok := characterSelectionMap[instance]

	if ok {
		return characterSelection_
	}

	characterSelectionMap[instance] = &characterSelection{PacketId: CharacterSelectionID}
	return characterSelectionMap[instance]
}

func (c *characterSelection) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt64(buff, c.id)
}

func (c *characterSelection) Deserialize(reader *bytes.Reader) {
	c.id = float64(utils.ReadVarUInt64(reader))
}

func (c *characterSelection) GetPacketId() uint32 {
	return c.PacketId
}

func (c *characterSelection) String() string {
	return fmt.Sprintf("packetId: %d\n", c.PacketId)
}
