// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 22:18:46.6473524 +0200 CEST m=+38.220550501

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type characterCharacteristicForPreset struct {
	PacketId                               uint32
	simpleCharacterCharacteristicForPreset *simpleCharacterCharacteristicForPreset
	stuff                                  int32
}

var characterCharacteristicForPresetMap = make(map[uint]*characterCharacteristicForPreset)

func (ch *characterCharacteristicForPreset) GetNOA(instance uint) Message {
	characterCharacteristicForPreset_, ok := characterCharacteristicForPresetMap[instance]

	if ok {
		return characterCharacteristicForPreset_
	}

	characterCharacteristicForPresetMap[instance] = &characterCharacteristicForPreset{PacketId: CharacterCharacteristicForPresetID}
	return characterCharacteristicForPresetMap[instance]
}

func (ch *characterCharacteristicForPreset) Serialize(buff *bytes.Buffer) {
	ch.simpleCharacterCharacteristicForPreset.Serialize(buff)
	utils.WriteVarInt16(buff, ch.stuff)
}

func (ch *characterCharacteristicForPreset) Deserialize(reader *bytes.Reader) {
	ch.simpleCharacterCharacteristicForPreset = new(simpleCharacterCharacteristicForPreset)
	ch.simpleCharacterCharacteristicForPreset.Deserialize(reader)
	ch.stuff = utils.ReadVarInt16(reader)
}

func (ch *characterCharacteristicForPreset) GetPacketId() uint32 {
	return ch.PacketId
}

func (ch *characterCharacteristicForPreset) String() string {
	return fmt.Sprintf("packetId: %d\n", ch.PacketId)
}
