// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-28 17:20:53.8879696 +0200 CEST m=+0.020059301

package messages

import (
	"bytes"
	"fmt"
)

type charactersListRequest struct {
	PacketId uint32
}

var charactersListRequestMap = make(map[uint]*charactersListRequest)

func GetCharactersListRequestNOA(instance uint) *charactersListRequest {
	charactersListRequest_, ok := charactersListRequestMap[instance]

	if ok {
		return charactersListRequest_
	}

	charactersListRequestMap[instance] = &charactersListRequest{PacketId: CharactersListRequestID}
	return charactersListRequestMap[instance]
}

func (c *charactersListRequest) Serialize(buff *bytes.Buffer) {

}

func (c *charactersListRequest) Deserialize(reader *bytes.Reader) {

}

func (c *charactersListRequest) GetPacketId() uint32 {
	return c.PacketId
}

func (c *charactersListRequest) String() string {
	return fmt.Sprintf("packetId: %d\n", c.PacketId)
}
