// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-28 21:11:33.7421392 +0200 CEST m=+0.020853701

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type characterBasicMinimalInformations struct {
	PacketId uint32
	aCI      *abstractCharacterInformation
	name     []byte
}

var characterBasicMinimalInformationsMap = make(map[uint]*characterBasicMinimalInformations)

func GetCharacterBasicMinimalInformationsNOA(instance uint) *characterBasicMinimalInformations {
	characterBasicMinimalInformations_, ok := characterBasicMinimalInformationsMap[instance]

	if ok {
		return characterBasicMinimalInformations_
	}

	characterBasicMinimalInformationsMap[instance] = &characterBasicMinimalInformations{PacketId: CharacterBasicMinimalInformationsID}
	return characterBasicMinimalInformationsMap[instance]
}

func (c *characterBasicMinimalInformations) Serialize(buff *bytes.Buffer) {
	c.aCI.Serialize(buff)
	utils.WriteUTF(buff, c.name)
}

func (c *characterBasicMinimalInformations) Deserialize(reader *bytes.Reader) {
	c.aCI.Deserialize(reader)
	c.name = utils.ReadUTF(reader)
}

func (c *characterBasicMinimalInformations) GetPacketId() uint32 {
	return c.PacketId
}

func (c *characterBasicMinimalInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", c.PacketId)
}
