// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 08:39:53.7215403 +0200 CEST m=+0.021221901

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type CharacterSelection struct {
	PacketId uint32
	Id       float64
}

var characterSelectionMap = make(map[uint]*CharacterSelection)

func (c *CharacterSelection) GetNOA(instance uint) Message {
	characterSelection_, ok := characterSelectionMap[instance]

	if ok {
		return characterSelection_
	}

	characterSelectionMap[instance] = &CharacterSelection{PacketId: CharacterSelectionID}
	return characterSelectionMap[instance]
}

func (c *CharacterSelection) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt64(buff, c.Id)
}

func (c *CharacterSelection) Deserialize(reader *bytes.Reader) {
	c.Id = float64(utils.ReadVarUInt64(reader))
}

func (c *CharacterSelection) GetPacketId() uint32 {
	return c.PacketId
}

func (c *CharacterSelection) String() string {
	return fmt.Sprintf("packetId: %d\n", c.PacketId)
}
