// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-28 20:33:27.2557034 +0200 CEST m=+0.020951601

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type characterMinimalInformations struct {
	PacketId uint32
	cBMI     *characterBasicMinimalInformations
	level    int32
}

var characterMinimalInformationsMap = make(map[uint]*characterMinimalInformations)

func (c *characterMinimalInformations) GetNOA(instance uint) Message {
	characterMinimalInformations_, ok := characterMinimalInformationsMap[instance]

	if ok {
		return characterMinimalInformations_
	}

	characterMinimalInformationsMap[instance] = &characterMinimalInformations{PacketId: CharacterMinimalInformationsID}
	return characterMinimalInformationsMap[instance]
}

func (c *characterMinimalInformations) Serialize(buff *bytes.Buffer) {
	c.cBMI.Serialize(buff)
	utils.WriteVarInt16(buff, c.level)
}

func (c *characterMinimalInformations) Deserialize(reader *bytes.Reader) {
	c.cBMI = new(characterBasicMinimalInformations)
	c.cBMI.Deserialize(reader)
	c.level = utils.ReadVarInt16(reader)
}

func (c *characterMinimalInformations) GetPacketId() uint32 {
	return c.PacketId
}

func (c *characterMinimalInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", c.PacketId)
}
