// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 16:05:59.2063163 +0200 CEST m=+1.364970701

package messages

import (
	"bytes"
	"fmt"
)

type characterLoadingComplete struct {
	PacketId uint32
}

var characterLoadingCompleteMap = make(map[uint]*characterLoadingComplete)

func GetCharacterLoadingCompleteNOA(instance uint) *characterLoadingComplete {
	characterLoadingComplete_, ok := characterLoadingCompleteMap[instance]

	if ok {
		return characterLoadingComplete_
	}

	characterLoadingCompleteMap[instance] = &characterLoadingComplete{PacketId: CharacterLoadingCompleteID}
	return characterLoadingCompleteMap[instance]
}

func (ch *characterLoadingComplete) Serialize(buff *bytes.Buffer) {
}

func (ch *characterLoadingComplete) Deserialize(reader *bytes.Reader) {
}

func (ch *characterLoadingComplete) GetPacketId() uint32 {
	return ch.PacketId
}

func (ch *characterLoadingComplete) String() string {
	return fmt.Sprintf("packetId: %d\n", ch.PacketId)
}
