// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-25 13:49:18.9644378 +0200 CEST m=+0.003136701

package messages

import (
	"bytes"
	"fmt"
)

type checkIntegrity struct {
	PacketId uint32
}

var checkIntegrity_ = &checkIntegrity{PacketId: CheckIntegrity}

func GetCheckIntegrityNOA() *checkIntegrity {
	return checkIntegrity_
}

func (c *checkIntegrity) Serialize(buff *bytes.Buffer) {

}

func (c *checkIntegrity) Deserialize(reader *bytes.Reader) {

}

func (c *checkIntegrity) GetPacketId() uint32 {
	return c.PacketId
}

func (c *checkIntegrity) String() string {
	return fmt.Sprintf("packetId: %d\n", c.PacketId)
}
