// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-25 09:52:40.4777026 +0200 CEST m=+0.003050901

package messages

import (
	"bytes"
	"fmt"
)

type credentialsAcknowledgement struct {
	PacketId uint32
}

var credentialsAcknowledgement_ = make(map[uint]*credentialsAcknowledgement)

func GetCredentialsAcknowledgementNOA(instance uint) *credentialsAcknowledgement {
	clientKey_, ok := credentialsAcknowledgement_[instance]

	if ok {
		return clientKey_
	}

	credentialsAcknowledgement_[instance] = &credentialsAcknowledgement{PacketId: CredentialsAcknowledgementID}
	return clientKey_
}

func (c *credentialsAcknowledgement) Serialize(buff *bytes.Buffer) {

}

func (c *credentialsAcknowledgement) Deserialize(reader *bytes.Reader) {

}

func (c *credentialsAcknowledgement) GetPacketId() uint32 {
	return c.PacketId
}

func (c *credentialsAcknowledgement) String() string {
	return fmt.Sprintf("PacketId: %d\n", c.PacketId)
}
