// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-31 17:06:48.6554648 +0200 CEST m=+25.460517501

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type currentMap struct {
	PacketId uint32
	mapId    float64
	mapKey   []byte
}

var currentMapMap = make(map[uint]*currentMap)

func (cu *currentMap) GetNOA(instance uint) Message {
	currentMap_, ok := currentMapMap[instance]

	if ok {
		return currentMap_
	}

	currentMapMap[instance] = &currentMap{PacketId: CurrentMapID}
	return currentMapMap[instance]
}

func (cu *currentMap) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, cu.mapId)
	utils.WriteUTF(buff, cu.mapKey)
}

func (cu *currentMap) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &cu.mapId)
	cu.mapKey = utils.ReadUTF(reader)
}

func (cu *currentMap) GetPacketId() uint32 {
	return cu.PacketId
}

func (cu *currentMap) String() string {
	return fmt.Sprintf("packetId: %d\n", cu.PacketId)
}
