// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 22:16:09.7917754 +0200 CEST m=+56.812813201

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type entitiesPreset struct {
	PacketId  uint32
	preset    *preset
	iconId    uint16
	entityIds []int32
}

var entitiesPresetMap = make(map[uint]*entitiesPreset)

func GetEntitiesPresetNOA(instance uint) *entitiesPreset {
	entitiesPreset_, ok := entitiesPresetMap[instance]

	if ok {
		return entitiesPreset_
	}

	entitiesPresetMap[instance] = &entitiesPreset{PacketId: EntitiesPresetID}
	return entitiesPresetMap[instance]
}

func (en *entitiesPreset) Serialize(buff *bytes.Buffer) {
	en.preset.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, en.iconId)
	_ = binary.Write(buff, binary.BigEndian, uint16(len(en.entityIds)))
	for i := 0; i < len(en.entityIds); i++ {
		utils.WriteVarInt16(buff, en.entityIds[i])
	}
}

func (en *entitiesPreset) Deserialize(reader *bytes.Reader) {
	en.preset = new(preset)
	en.preset.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &en.iconId)
	var len2_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len2_)
	en.entityIds = nil
	for i := 0; i < int(len2_); i++ {
		en.entityIds = append(en.entityIds, utils.ReadVarInt16(reader))
	}
}

func (en *entitiesPreset) GetPacketId() uint32 {
	return en.PacketId
}

func (en *entitiesPreset) String() string {
	return fmt.Sprintf("packetId: %d\n", en.PacketId)
}
