// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 22:05:09.4008049 +0200 CEST m=+99.771809201

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type forgettableSpellsPreset struct {
	PacketId     uint32
	preset       *preset
	spellsPreset *spellsPreset
	sFPs         []*spellForPreset
}

var forgettableSpellsPresetMap = make(map[uint]*forgettableSpellsPreset)

func (fo *forgettableSpellsPreset) GetNOA(instance uint) Message {
	forgettableSpellsPreset_, ok := forgettableSpellsPresetMap[instance]

	if ok {
		return forgettableSpellsPreset_
	}

	forgettableSpellsPresetMap[instance] = &forgettableSpellsPreset{PacketId: ForgettableSpellsPresetID}
	return forgettableSpellsPresetMap[instance]
}

func (fo *forgettableSpellsPreset) Serialize(buff *bytes.Buffer) {
	fo.preset.Serialize(buff)
	fo.spellsPreset.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, uint16(len(fo.sFPs)))
	for i := 0; i < len(fo.sFPs); i++ {
		fo.sFPs[i].Serialize(buff)
	}
}

func (fo *forgettableSpellsPreset) Deserialize(reader *bytes.Reader) {
	fo.preset = new(preset)
	fo.preset.Deserialize(reader)
	fo.spellsPreset = new(spellsPreset)
	fo.spellsPreset.Deserialize(reader)
	var len2_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len2_)
	fo.sFPs = nil
	for i := 0; i < int(len2_); i++ {
		aMessage2 := new(spellForPreset)
		aMessage2.Deserialize(reader)
		fo.sFPs = append(fo.sFPs, aMessage2)
	}
}

func (fo *forgettableSpellsPreset) GetPacketId() uint32 {
	return fo.PacketId
}

func (fo *forgettableSpellsPreset) String() string {
	return fmt.Sprintf("packetId: %d\n", fo.PacketId)
}
