// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 23:02:35.3234692 +0200 CEST m=+75.292288401

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type friendSpouseOnlineInformations struct {
	PacketId                  uint32
	friendSpouseInformations0 *friendSpouseInformations
	inFight                   bool
	followSpouse              bool
	mapId                     float64
	subAreaId                 int32
}

var friendSpouseOnlineInformationsMap = make(map[uint]*friendSpouseOnlineInformations)

func (fr *friendSpouseOnlineInformations) GetNOA(instance uint) Message {
	friendSpouseOnlineInformations_, ok := friendSpouseOnlineInformationsMap[instance]

	if ok {
		return friendSpouseOnlineInformations_
	}

	friendSpouseOnlineInformationsMap[instance] = &friendSpouseOnlineInformations{PacketId: FriendSpouseOnlineInformationsID}
	return friendSpouseOnlineInformationsMap[instance]
}

func (fr *friendSpouseOnlineInformations) Serialize(buff *bytes.Buffer) {
	fr.friendSpouseInformations0.Serialize(buff)
	var box1 uint32
	box1 = utils.SetFlag(box1, 0, fr.inFight)
	box1 = utils.SetFlag(box1, 1, fr.followSpouse)
	_ = binary.Write(buff, binary.BigEndian, byte(box1))
	_ = binary.Write(buff, binary.BigEndian, fr.mapId)
	utils.WriteVarInt16(buff, fr.subAreaId)
}

func (fr *friendSpouseOnlineInformations) Deserialize(reader *bytes.Reader) {
	fr.friendSpouseInformations0 = new(friendSpouseInformations)
	fr.friendSpouseInformations0.Deserialize(reader)
	var box1 byte
	_ = binary.Read(reader, binary.BigEndian, &box1)
	fr.inFight = utils.GetFlag(uint32(box1), 0)
	fr.followSpouse = utils.GetFlag(uint32(box1), 1)
	_ = binary.Read(reader, binary.BigEndian, &fr.mapId)
	fr.subAreaId = utils.ReadVarInt16(reader)
}

func (fr *friendSpouseOnlineInformations) GetPacketId() uint32 {
	return fr.PacketId
}

func (fr *friendSpouseOnlineInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", fr.PacketId)
}
