// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 22:54:28.3638326 +0200 CEST m=+72.889591301

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type friendInformations struct {
	PacketId                     uint32
	abstractContactInformations0 *abstractContactInformations
	playerState                  byte
	lastConnection               int32
	achievementPoints            int32
	leagueId                     int32
	ladderPosition               int32
}

var friendInformationsMap = make(map[uint]*friendInformations)

func (fr *friendInformations) GetNOA(instance uint) Message {
	friendInformations_, ok := friendInformationsMap[instance]

	if ok {
		return friendInformations_
	}

	friendInformationsMap[instance] = &friendInformations{PacketId: FriendInformationsID}
	return friendInformationsMap[instance]
}

func (fr *friendInformations) Serialize(buff *bytes.Buffer) {
	fr.abstractContactInformations0.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, fr.playerState)
	utils.WriteVarInt16(buff, fr.lastConnection)
	_ = binary.Write(buff, binary.BigEndian, fr.achievementPoints)
	utils.WriteVarInt16(buff, fr.leagueId)
	_ = binary.Write(buff, binary.BigEndian, fr.ladderPosition)
}

func (fr *friendInformations) Deserialize(reader *bytes.Reader) {
	fr.abstractContactInformations0 = new(abstractContactInformations)
	fr.abstractContactInformations0.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &fr.playerState)
	fr.lastConnection = utils.ReadVarInt16(reader)
	_ = binary.Read(reader, binary.BigEndian, &fr.achievementPoints)
	fr.leagueId = utils.ReadVarInt16(reader)
	_ = binary.Read(reader, binary.BigEndian, &fr.ladderPosition)
}

func (fr *friendInformations) GetPacketId() uint32 {
	return fr.PacketId
}

func (fr *friendInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", fr.PacketId)
}
