// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 23:00:38.979688 +0200 CEST m=+102.439358401

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type friendSpouseInformations struct {
	PacketId           uint32
	spouseAccountId    int32
	spouseId           float64
	spouseName         []byte
	spouseLevel        int32
	breed              byte
	sex                byte
	entityLook6        *entityLook
	guildInformations7 *guildInformations
	alignmentSide      byte
}

var friendSpouseInformationsMap = make(map[uint]*friendSpouseInformations)

func (fr *friendSpouseInformations) GetNOA(instance uint) Message {
	friendSpouseInformations_, ok := friendSpouseInformationsMap[instance]

	if ok {
		return friendSpouseInformations_
	}

	friendSpouseInformationsMap[instance] = &friendSpouseInformations{PacketId: FriendSpouseInformationsID}
	return friendSpouseInformationsMap[instance]
}

func (fr *friendSpouseInformations) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, fr.spouseAccountId)
	utils.WriteVarInt64(buff, fr.spouseId)
	utils.WriteUTF(buff, fr.spouseName)
	utils.WriteVarInt16(buff, fr.spouseLevel)
	_ = binary.Write(buff, binary.BigEndian, fr.breed)
	_ = binary.Write(buff, binary.BigEndian, fr.sex)
	fr.entityLook6.Serialize(buff)
	fr.guildInformations7.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, fr.alignmentSide)
}

func (fr *friendSpouseInformations) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &fr.spouseAccountId)
	fr.spouseId = float64(utils.ReadVarInt64(reader))
	fr.spouseName = utils.ReadUTF(reader)
	fr.spouseLevel = utils.ReadVarInt16(reader)
	_ = binary.Read(reader, binary.BigEndian, &fr.breed)
	_ = binary.Read(reader, binary.BigEndian, &fr.sex)
	fr.entityLook6 = new(entityLook)
	fr.entityLook6.Deserialize(reader)
	fr.guildInformations7 = new(guildInformations)
	fr.guildInformations7.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &fr.alignmentSide)
}

func (fr *friendSpouseInformations) GetPacketId() uint32 {
	return fr.PacketId
}

func (fr *friendSpouseInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", fr.PacketId)
}
