// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 22:57:58.4510486 +0200 CEST m=+151.188448001

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type friendOnlineInformations struct {
	PacketId            uint32
	friendInformations0 *friendInformations
	sex                 bool
	havenBagShared      bool
	playerId            float64
	playerName          []byte
	level               int32
	alignmentSide       byte
	breed               byte
	guildInformations7  *guildInformations
	moodSmileyId        int32
	item9               *item
}

var friendOnlineInformationsMap = make(map[uint]*friendOnlineInformations)

func (fr *friendOnlineInformations) GetNOA(instance uint) Message {
	friendOnlineInformations_, ok := friendOnlineInformationsMap[instance]

	if ok {
		return friendOnlineInformations_
	}

	friendOnlineInformationsMap[instance] = &friendOnlineInformations{PacketId: FriendOnlineInformationsID}
	return friendOnlineInformationsMap[instance]
}

func (fr *friendOnlineInformations) Serialize(buff *bytes.Buffer) {
	fr.friendInformations0.Serialize(buff)
	var box1 uint32
	box1 = utils.SetFlag(box1, 0, fr.sex)
	box1 = utils.SetFlag(box1, 1, fr.havenBagShared)
	_ = binary.Write(buff, binary.BigEndian, byte(box1))
	utils.WriteVarInt64(buff, fr.playerId)
	utils.WriteUTF(buff, fr.playerName)
	utils.WriteVarInt16(buff, fr.level)
	_ = binary.Write(buff, binary.BigEndian, fr.alignmentSide)
	_ = binary.Write(buff, binary.BigEndian, fr.breed)
	fr.guildInformations7.Serialize(buff)
	utils.WriteVarInt16(buff, fr.moodSmileyId)
	fr.item9.Serialize(buff)
}

func (fr *friendOnlineInformations) Deserialize(reader *bytes.Reader) {
	fr.friendInformations0 = new(friendInformations)
	fr.friendInformations0.Deserialize(reader)
	var box1 byte
	_ = binary.Read(reader, binary.BigEndian, &box1)
	fr.sex = utils.GetFlag(uint32(box1), 0)
	fr.havenBagShared = utils.GetFlag(uint32(box1), 1)
	fr.playerId = float64(utils.ReadVarInt64(reader))
	fr.playerName = utils.ReadUTF(reader)
	fr.level = utils.ReadVarInt16(reader)
	_ = binary.Read(reader, binary.BigEndian, &fr.alignmentSide)
	_ = binary.Read(reader, binary.BigEndian, &fr.breed)
	fr.guildInformations7 = new(guildInformations)
	fr.guildInformations7.Deserialize(reader)
	fr.moodSmileyId = utils.ReadVarInt16(reader)
	fr.item9 = new(item)
	fr.item9.Deserialize(reader)
}

func (fr *friendOnlineInformations) GetPacketId() uint32 {
	return fr.PacketId
}

func (fr *friendOnlineInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", fr.PacketId)
}
