// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 22:01:08.7045326 +0200 CEST m=+0.518525901

package messages

import (
	"bytes"
	"fmt"
)

type friendsGetList struct {
	PacketId uint32
}

var friendsGetListMap = make(map[uint]*friendsGetList)

func (fr *friendsGetList) GetNOA(instance uint) Message {
	friendsGetList_, ok := friendsGetListMap[instance]

	if ok {
		return friendsGetList_
	}

	friendsGetListMap[instance] = &friendsGetList{PacketId: FriendsGetListID}
	return friendsGetListMap[instance]
}

func (fr *friendsGetList) Serialize(buff *bytes.Buffer) {
}

func (fr *friendsGetList) Deserialize(reader *bytes.Reader) {
}

func (fr *friendsGetList) GetPacketId() uint32 {
	return fr.PacketId
}

func (fr *friendsGetList) String() string {
	return fmt.Sprintf("packetId: %d\n", fr.PacketId)
}
