// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 09:43:38.592207 +0200 CEST m=+4.757416701

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type friendGuildWarnOnAchievementCompleteState struct {
	PacketId uint32
	enable   bool
}

var friendGuildWarnOnAchievementCompleteStateMap = make(map[uint]*friendGuildWarnOnAchievementCompleteState)

func (fr *friendGuildWarnOnAchievementCompleteState) GetNOA(instance uint) Message {
	friendGuildWarnOnAchievementCompleteState_, ok := friendGuildWarnOnAchievementCompleteStateMap[instance]

	if ok {
		return friendGuildWarnOnAchievementCompleteState_
	}

	friendGuildWarnOnAchievementCompleteStateMap[instance] = &friendGuildWarnOnAchievementCompleteState{PacketId: FriendGuildWarnOnAchievementCompleteStateID}
	return friendGuildWarnOnAchievementCompleteStateMap[instance]
}

func (fr *friendGuildWarnOnAchievementCompleteState) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, fr.enable)
}

func (fr *friendGuildWarnOnAchievementCompleteState) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &fr.enable)
}

func (fr *friendGuildWarnOnAchievementCompleteState) GetPacketId() uint32 {
	return fr.PacketId
}

func (fr *friendGuildWarnOnAchievementCompleteState) String() string {
	return fmt.Sprintf("packetId: %d\n", fr.PacketId)
}
