// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 16:01:02.4872266 +0200 CEST m=+25.820650701

package messages

import (
	"bytes"
	"fmt"
)

type gameRolePlayArenaUpdatePlayerInfosAllQueues struct {
	PacketId                           uint32
	gameRolePlayArenaUpdatePlayerInfos *gameRolePlayArenaUpdatePlayerInfos
	team                               *arenaRankInfos
	duel                               *arenaRankInfos
}

var gameRolePlayArenaUpdatePlayerInfosAllQueuesMap = make(map[uint]*gameRolePlayArenaUpdatePlayerInfosAllQueues)

func (ga *gameRolePlayArenaUpdatePlayerInfosAllQueues) GetNOA(instance uint) Message {
	gameRolePlayArenaUpdatePlayerInfosAllQueues_, ok := gameRolePlayArenaUpdatePlayerInfosAllQueuesMap[instance]

	if ok {
		return gameRolePlayArenaUpdatePlayerInfosAllQueues_
	}

	gameRolePlayArenaUpdatePlayerInfosAllQueuesMap[instance] = &gameRolePlayArenaUpdatePlayerInfosAllQueues{PacketId: GameRolePlayArenaUpdatePlayerInfosAllQueuesID}
	return gameRolePlayArenaUpdatePlayerInfosAllQueuesMap[instance]
}

func (ga *gameRolePlayArenaUpdatePlayerInfosAllQueues) Serialize(buff *bytes.Buffer) {
	ga.gameRolePlayArenaUpdatePlayerInfos.Serialize(buff)
	ga.team.Serialize(buff)
	ga.duel.Serialize(buff)
}

func (ga *gameRolePlayArenaUpdatePlayerInfosAllQueues) Deserialize(reader *bytes.Reader) {
	ga.gameRolePlayArenaUpdatePlayerInfos = new(gameRolePlayArenaUpdatePlayerInfos)
	ga.gameRolePlayArenaUpdatePlayerInfos.Deserialize(reader)
	ga.team = new(arenaRankInfos)
	ga.team.Deserialize(reader)
	ga.duel = new(arenaRankInfos)
	ga.duel.Deserialize(reader)
}

func (ga *gameRolePlayArenaUpdatePlayerInfosAllQueues) GetPacketId() uint32 {
	return ga.PacketId
}

func (ga *gameRolePlayArenaUpdatePlayerInfosAllQueues) String() string {
	return fmt.Sprintf("packetId: %d\n", ga.PacketId)
}
