// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 23:14:41.5536181 +0200 CEST m=+1.048234201

package messages

import (
	"bytes"
	"fmt"
)

type gameContextDestroy struct {
	PacketId uint32
}

var gameContextDestroyMap = make(map[uint]*gameContextDestroy)

func (ga *gameContextDestroy) GetNOA(instance uint) Message {
	gameContextDestroy_, ok := gameContextDestroyMap[instance]

	if ok {
		return gameContextDestroy_
	}

	gameContextDestroyMap[instance] = &gameContextDestroy{PacketId: GameContextDestroyID}
	return gameContextDestroyMap[instance]
}

func (ga *gameContextDestroy) Serialize(buff *bytes.Buffer) {
}

func (ga *gameContextDestroy) Deserialize(reader *bytes.Reader) {
}

func (ga *gameContextDestroy) GetPacketId() uint32 {
	return ga.PacketId
}

func (ga *gameContextDestroy) String() string {
	return fmt.Sprintf("packetId: %d\n", ga.PacketId)
}
