// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 15:58:12.7930681 +0200 CEST m=+53.188788901

package messages

import (
	"bytes"
	"fmt"
)

type gameRolePlayArenaUpdatePlayerInfos struct {
	PacketId       uint32
	arenaRankInfos *arenaRankInfos
}

var gameRolePlayArenaUpdatePlayerInfosMap = make(map[uint]*gameRolePlayArenaUpdatePlayerInfos)

func GetGameRolePlayArenaUpdatePlayerInfosNOA(instance uint) *gameRolePlayArenaUpdatePlayerInfos {
	gameRolePlayArenaUpdatePlayerInfos_, ok := gameRolePlayArenaUpdatePlayerInfosMap[instance]

	if ok {
		return gameRolePlayArenaUpdatePlayerInfos_
	}

	gameRolePlayArenaUpdatePlayerInfosMap[instance] = &gameRolePlayArenaUpdatePlayerInfos{PacketId: GameRolePlayArenaUpdatePlayerInfosID}
	return gameRolePlayArenaUpdatePlayerInfosMap[instance]
}

func (ga *gameRolePlayArenaUpdatePlayerInfos) Serialize(buff *bytes.Buffer) {
	ga.arenaRankInfos.Serialize(buff)
}

func (ga *gameRolePlayArenaUpdatePlayerInfos) Deserialize(reader *bytes.Reader) {
	ga.arenaRankInfos = new(arenaRankInfos)
	ga.arenaRankInfos.Deserialize(reader)
}

func (ga *gameRolePlayArenaUpdatePlayerInfos) GetPacketId() uint32 {
	return ga.PacketId
}

func (ga *gameRolePlayArenaUpdatePlayerInfos) String() string {
	return fmt.Sprintf("packetId: %d\n", ga.PacketId)
}
