// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 12:16:45.4124177 +0200 CEST m=+29.306412901

package messages

import (
	"bytes"
	"fmt"
)

type GameContextActorInformations struct {
	PacketId                              uint32
	GameContextActorPositionInformations0 *GameContextActorPositionInformations
	EntityLook1                           *EntityLook
}

var GameContextActorInformationsMap = make(map[uint]*GameContextActorInformations)

func (Ga *GameContextActorInformations) GetNOA(instance uint) Message {
	GameContextActorInformations_, ok := GameContextActorInformationsMap[instance]

	if ok {
		return GameContextActorInformations_
	}

	GameContextActorInformationsMap[instance] = &GameContextActorInformations{PacketId: GameContextActorInformationsID}
	return GameContextActorInformationsMap[instance]
}

func (Ga *GameContextActorInformations) Serialize(buff *bytes.Buffer) {
	Ga.GameContextActorPositionInformations0.Serialize(buff)
	Ga.EntityLook1.Serialize(buff)
}

func (Ga *GameContextActorInformations) Deserialize(reader *bytes.Reader) {
	Ga.GameContextActorPositionInformations0 = new(GameContextActorPositionInformations)
	Ga.GameContextActorPositionInformations0.Deserialize(reader)
	Ga.EntityLook1 = new(EntityLook)
	Ga.EntityLook1.Deserialize(reader)
}

func (Ga *GameContextActorInformations) GetPacketId() uint32 {
	return Ga.PacketId
}

func (Ga *GameContextActorInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", Ga.PacketId)
}
