// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 12:18:11.0845214 +0200 CEST m=+6.513861201

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type GameRolePlayActorInformations struct {
	PacketId                      uint32
	typeId                        int16
	GameContextActorInformations0 *GameContextActorInformations
}

var GameRolePlayActorInformationsMap = make(map[uint]*GameRolePlayActorInformations)

func (Ga *GameRolePlayActorInformations) GetNOA(instance uint) Message {
	GameRolePlayActorInformations_, ok := GameRolePlayActorInformationsMap[instance]

	if ok {
		return GameRolePlayActorInformations_
	}

	GameRolePlayActorInformationsMap[instance] = &GameRolePlayActorInformations{PacketId: GameRolePlayActorInformationsID}
	return GameRolePlayActorInformationsMap[instance]
}

func (Ga *GameRolePlayActorInformations) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, Ga.typeId)
	Ga.GameContextActorInformations0.Serialize(buff)
}

func (Ga *GameRolePlayActorInformations) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &Ga.typeId)
	Ga.GameContextActorInformations0 = new(GameContextActorInformations)
	Ga.GameContextActorInformations0.Deserialize(reader)
}

func (Ga *GameRolePlayActorInformations) GetPacketId() uint32 {
	return Ga.PacketId
}

func (Ga *GameRolePlayActorInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", Ga.PacketId)
}
