// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 12:15:48.0041811 +0200 CEST m=+20.588393901

package messages

import (
	"bytes"
	"fmt"
)

type GameRolePlayActorInformations struct {
	PacketId uint32
}

var GameRolePlayActorInformationsMap = make(map[uint]*GameRolePlayActorInformations)

func (Ga *GameRolePlayActorInformations) GetNOA(instance uint) Message {
	GameRolePlayActorInformations_, ok := GameRolePlayActorInformationsMap[instance]

	if ok {
		return GameRolePlayActorInformations_
	}

	GameRolePlayActorInformationsMap[instance] = &GameRolePlayActorInformations{PacketId: GameRolePlayActorInformationsID}
	return GameRolePlayActorInformationsMap[instance]
}

func (Ga *GameRolePlayActorInformations) Serialize(buff *bytes.Buffer) {
}

func (Ga *GameRolePlayActorInformations) Deserialize(reader *bytes.Reader) {
}

func (Ga *GameRolePlayActorInformations) GetPacketId() uint32 {
	return Ga.PacketId
}

func (Ga *GameRolePlayActorInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", Ga.PacketId)
}
