// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 22:05:55.7442929 +0200 CEST m=+0.798536501

package messages

import (
	"bytes"
	"fmt"
)

type gameContextCreateRequest struct {
	PacketId uint32
}

var gameContextCreateRequestMap = make(map[uint]*gameContextCreateRequest)

func (ga *gameContextCreateRequest) GetNOA(instance uint) Message {
	gameContextCreateRequest_, ok := gameContextCreateRequestMap[instance]

	if ok {
		return gameContextCreateRequest_
	}

	gameContextCreateRequestMap[instance] = &gameContextCreateRequest{PacketId: GameContextCreateRequestID}
	return gameContextCreateRequestMap[instance]
}

func (ga *gameContextCreateRequest) Serialize(buff *bytes.Buffer) {
}

func (ga *gameContextCreateRequest) Deserialize(reader *bytes.Reader) {
}

func (ga *gameContextCreateRequest) GetPacketId() uint32 {
	return ga.PacketId
}

func (ga *gameContextCreateRequest) String() string {
	return fmt.Sprintf("packetId: %d\n", ga.PacketId)
}
