// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-25 10:47:08.6457558 +0200 CEST m=+0.002560401

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type gameServerInformations struct {
	PacketId        uint32
	isMonoAccount   bool
	isSelectable    bool
	id              uint16
	type_           byte
	status          byte
	completion      byte
	charactersCount byte
	charactersSlots byte
	date            float64
}

var gameServerInformations_ = &gameServerInformations{PacketId: gameServerInformationID}

func GetGameServerInformationsNOA() *gameServerInformations {
	return gameServerInformations_
}

func (g *gameServerInformations) Serialize(buff *bytes.Buffer) {

}

func (g *gameServerInformations) Deserialize(reader *bytes.Reader) {
	var box byte
	_ = binary.Read(reader, binary.BigEndian, &box)

	g.isMonoAccount = utils.GetFlag(uint32(box), 0)
	g.isSelectable = utils.GetFlag(uint32(box), 1)

	_ = binary.Read(reader, binary.BigEndian, &g.id)
	_ = binary.Read(reader, binary.BigEndian, &g.type_)
	_ = binary.Read(reader, binary.BigEndian, &g.status)
	_ = binary.Read(reader, binary.BigEndian, &g.completion)
	_ = binary.Read(reader, binary.BigEndian, &g.charactersCount)
	_ = binary.Read(reader, binary.BigEndian, &g.charactersSlots)
	_ = binary.Read(reader, binary.BigEndian, &g.date)
}

func (g *gameServerInformations) GetPacketId() uint32 {
	return g.PacketId
}

func (g *gameServerInformations) String(reader *bytes.Reader) string {
	return fmt.Sprintf("PacketId: %d\n", g.PacketId)
}
