// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-28 19:54:55.9709977 +0200 CEST m=+0.019736701

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type haapiApiKey struct {
	PacketId uint32
	token    []byte
}

var haapiApiKeyMap = make(map[uint]*haapiApiKey)

func (h *haapiApiKey) GetNOA(instance uint) Message {
	haapiApiKey_, ok := haapiApiKeyMap[instance]

	if ok {
		return haapiApiKey_
	}

	haapiApiKeyMap[instance] = &haapiApiKey{PacketId: HaapiApiKeyID}
	return haapiApiKeyMap[instance]
}

func (h *haapiApiKey) Serialize(buff *bytes.Buffer) {
	utils.WriteUTF(buff, h.token)
}

func (h *haapiApiKey) Deserialize(reader *bytes.Reader) {
	h.token = utils.ReadUTF(reader)
}

func (h *haapiApiKey) GetPacketId() uint32 {
	return h.PacketId
}

func (h *haapiApiKey) String() string {
	return fmt.Sprintf("packetId: %d\n", h.PacketId)
}
