// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 08:59:53.0591825 +0200 CEST m=+0.022020601

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type havenBagRoomUpdate struct {
	PacketId uint32
	action   byte
	hBRPI    []*havenBagRoomPreviewInformation
}

var havenBagRoomUpdateMap = make(map[uint]*havenBagRoomUpdate)

func GetHavenBagRoomUpdateNOA(instance uint) *havenBagRoomUpdate {
	havenBagRoomUpdate_, ok := havenBagRoomUpdateMap[instance]

	if ok {
		return havenBagRoomUpdate_
	}

	havenBagRoomUpdateMap[instance] = &havenBagRoomUpdate{PacketId: HavenBagRoomUpdateID}
	return havenBagRoomUpdateMap[instance]
}

func (h *havenBagRoomUpdate) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, h.action)
	_ = binary.Write(buff, binary.BigEndian, uint16(len(h.hBRPI)))

	for i := 0; i < len(h.hBRPI); i++ {
		h.hBRPI[i].Serialize(buff)
	}
}

func (h *havenBagRoomUpdate) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &h.action)

	var len_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len_)
	h.hBRPI = nil
	for i := 0; i < int(len_); i++ {
		aHBRPI := new(havenBagRoomPreviewInformation)
		aHBRPI.Deserialize(reader)
		h.hBRPI = append(h.hBRPI, aHBRPI)
	}
}

func (h *havenBagRoomUpdate) GetPacketId() uint32 {
	return h.PacketId
}

func (h *havenBagRoomUpdate) String() string {
	return fmt.Sprintf("packetId: %d\n", h.PacketId)
}
