// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 15:23:48.1873053 +0200 CEST m=+88.940824801

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type houseInstanceInformations struct {
	PacketId              uint32
	secondHand            bool
	isLocked              bool
	hasOwner              bool
	isSaleLocked          bool
	instanceId            int32
	accountTagInformation *accountTagInformation
	price                 float64
}

var huseInstanceInformationsMap = make(map[uint]*houseInstanceInformations)

func GetHuseInstanceInformationsNOA(instance uint) *houseInstanceInformations {
	huseInstanceInformations_, ok := huseInstanceInformationsMap[instance]

	if ok {
		return huseInstanceInformations_
	}

	huseInstanceInformationsMap[instance] = &houseInstanceInformations{PacketId: HouseInstanceInformationsID}
	return huseInstanceInformationsMap[instance]
}

func (hu *houseInstanceInformations) Serialize(buff *bytes.Buffer) {
	var box0 uint32
	box0 = utils.SetFlag(box0, 0, hu.secondHand)
	box0 = utils.SetFlag(box0, 1, hu.isLocked)
	box0 = utils.SetFlag(box0, 2, hu.hasOwner)
	box0 = utils.SetFlag(box0, 3, hu.isSaleLocked)
	_ = binary.Write(buff, binary.BigEndian, byte(box0))
	_ = binary.Write(buff, binary.BigEndian, hu.instanceId)
	hu.accountTagInformation.Serialize(buff)
	utils.WriteVarUInt64(buff, hu.price)
}

func (hu *houseInstanceInformations) Deserialize(reader *bytes.Reader) {
	var box0 byte
	_ = binary.Read(reader, binary.BigEndian, &box0)
	hu.secondHand = utils.GetFlag(uint32(box0), 0)
	hu.isLocked = utils.GetFlag(uint32(box0), 1)
	hu.hasOwner = utils.GetFlag(uint32(box0), 2)
	hu.isSaleLocked = utils.GetFlag(uint32(box0), 3)
	_ = binary.Read(reader, binary.BigEndian, &hu.instanceId)
	hu.accountTagInformation = new(accountTagInformation)
	hu.accountTagInformation.Deserialize(reader)
	hu.price = float64(utils.ReadVarUInt64(reader))
}

func (hu *houseInstanceInformations) GetPacketId() uint32 {
	return hu.PacketId
}

func (hu *houseInstanceInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", hu.PacketId)
}
