// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 15:19:08.5552546 +0200 CEST m=+120.552571601

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type houseInformationsForGuild struct {
	PacketId              uint32
	houseInformations     *houseInformations
	instanceId            int32
	secondHand            bool
	accountTagInformation *accountTagInformation
	worldX                uint16
	worldY                uint16
	mapId                 float64
	subAreaId             int32
	skillListIds          []int32
	guildshareParams      int32
}

var houseInformationsForGuildMap = make(map[uint]*houseInformationsForGuild)

func (ho *houseInformationsForGuild) GetNOA(instance uint) Message {
	houseInformationsForGuild_, ok := houseInformationsForGuildMap[instance]

	if ok {
		return houseInformationsForGuild_
	}

	houseInformationsForGuildMap[instance] = &houseInformationsForGuild{PacketId: HouseInformationsForGuildID}
	return houseInformationsForGuildMap[instance]
}

func (ho *houseInformationsForGuild) Serialize(buff *bytes.Buffer) {
	ho.houseInformations.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, ho.instanceId)
	_ = binary.Write(buff, binary.BigEndian, ho.secondHand)
	ho.accountTagInformation.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, ho.worldX)
	_ = binary.Write(buff, binary.BigEndian, ho.worldY)
	_ = binary.Write(buff, binary.BigEndian, ho.mapId)
	utils.WriteVarInt16(buff, ho.subAreaId)
	_ = binary.Write(buff, binary.BigEndian, uint16(len(ho.skillListIds)))
	_ = binary.Write(buff, binary.BigEndian, ho.skillListIds)
	utils.WriteVarInt32(buff, ho.guildshareParams)
}

func (ho *houseInformationsForGuild) Deserialize(reader *bytes.Reader) {
	ho.houseInformations = new(houseInformations)
	ho.houseInformations.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &ho.instanceId)
	_ = binary.Read(reader, binary.BigEndian, &ho.secondHand)
	ho.accountTagInformation = new(accountTagInformation)
	ho.accountTagInformation.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &ho.worldX)
	_ = binary.Read(reader, binary.BigEndian, &ho.worldY)
	_ = binary.Read(reader, binary.BigEndian, &ho.mapId)
	ho.subAreaId = utils.ReadVarInt16(reader)
	var len8_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len8_)
	ho.skillListIds = make([]int32, len8_)
	_ = binary.Read(reader, binary.BigEndian, ho.skillListIds)
	ho.guildshareParams = utils.ReadVarInt32(reader)
}

func (ho *houseInformationsForGuild) GetPacketId() uint32 {
	return ho.PacketId
}

func (ho *houseInformationsForGuild) String() string {
	return fmt.Sprintf("packetId: %d\n", ho.PacketId)
}
