// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 11:56:13.2391097 +0200 CEST m=+33.533913101

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type HouseInformations struct {
	PacketId uint32
	houseId  int32
	modelId  int32
}

var HouseInformationsMap = make(map[uint]*HouseInformations)

func (Ho *HouseInformations) GetNOA(instance uint) Message {
	HouseInformations_, ok := HouseInformationsMap[instance]

	if ok {
		return HouseInformations_
	}

	HouseInformationsMap[instance] = &HouseInformations{PacketId: HouseInformationsID}
	return HouseInformationsMap[instance]
}

func (Ho *HouseInformations) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt32(buff, Ho.houseId)
	utils.WriteVarInt16(buff, Ho.modelId)
}

func (Ho *HouseInformations) Deserialize(reader *bytes.Reader) {
	Ho.houseId = utils.ReadVarInt32(reader)
	Ho.modelId = utils.ReadVarInt16(reader)
}

func (Ho *HouseInformations) GetPacketId() uint32 {
	return Ho.PacketId
}

func (Ho *HouseInformations) String() string {
	return fmt.Sprintf("packetId: %d\n", Ho.PacketId)
}
