// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 14:55:47.5976276 +0200 CEST m=+40.897963801

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type idolList struct {
	PacketId         uint32
	chosenIdols      []int32
	partyChosenIdols []int32
	itemWrapper      *itemWrapper
}

var IdolListMap = make(map[uint]*idolList)

func (id *idolList) GetNOA(instance uint) Message {
	IdolList_, ok := IdolListMap[instance]

	if ok {
		return IdolList_
	}

	IdolListMap[instance] = &idolList{PacketId: IdolListID}
	return IdolListMap[instance]
}

func (id *idolList) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, uint16(len(id.chosenIdols)))
	for i := 0; i < len(id.chosenIdols); i++ {
		utils.WriteVarInt16(buff, id.chosenIdols[i])
	}
	_ = binary.Write(buff, binary.BigEndian, uint16(len(id.partyChosenIdols)))
	for i := 0; i < len(id.partyChosenIdols); i++ {
		utils.WriteVarInt16(buff, id.partyChosenIdols[i])
	}
	id.itemWrapper.Serialize(buff)
}

func (id *idolList) Deserialize(reader *bytes.Reader) {
	var len0_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len0_)
	id.chosenIdols = nil
	for i := 0; i < int(len0_); i++ {
		id.chosenIdols = append(id.chosenIdols, utils.ReadVarInt16(reader))
	}
	var len1_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len1_)
	id.partyChosenIdols = nil
	for i := 0; i < int(len1_); i++ {
		id.partyChosenIdols = append(id.partyChosenIdols, utils.ReadVarInt16(reader))
	}
	id.itemWrapper = new(itemWrapper)
	id.itemWrapper.Deserialize(reader)
}

func (id *idolList) GetPacketId() uint32 {
	return id.PacketId
}

func (id *idolList) String() string {
	return fmt.Sprintf("packetId: %d\n", id.PacketId)
}
