// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 22:13:58.9043574 +0200 CEST m=+72.507034701

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type idolsPreset struct {
	PacketId uint32
	preset   *preset
	iconId   uint16
	idolIds  []int32
}

var idolsPresetMap = make(map[uint]*idolsPreset)

func (id *idolsPreset) GetNOA(instance uint) Message {
	idolsPreset_, ok := idolsPresetMap[instance]

	if ok {
		return idolsPreset_
	}

	idolsPresetMap[instance] = &idolsPreset{PacketId: IdolsPresetID}
	return idolsPresetMap[instance]
}

func (id *idolsPreset) Serialize(buff *bytes.Buffer) {
	id.preset.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, id.iconId)
	_ = binary.Write(buff, binary.BigEndian, uint16(len(id.idolIds)))
	for i := 0; i < len(id.idolIds); i++ {
		utils.WriteVarInt16(buff, id.idolIds[i])
	}
}

func (id *idolsPreset) Deserialize(reader *bytes.Reader) {
	id.preset = new(preset)
	id.preset.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &id.iconId)
	var len2_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len2_)
	id.idolIds = nil
	for i := 0; i < int(len2_); i++ {
		id.idolIds = append(id.idolIds, utils.ReadVarInt16(reader))
	}
}

func (id *idolsPreset) GetPacketId() uint32 {
	return id.PacketId
}

func (id *idolsPreset) String() string {
	return fmt.Sprintf("packetId: %d\n", id.PacketId)
}
