// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-27 15:47:36.2626722 +0200 CEST m=+0.004216601

package messages

const (
	HelloConnectID                      = 1030
	IdentificationID                    = 2767
	ProtocolID                          = 9546
	TrustCertificateID                  = 2178
	VersionID                           = 9475
	IdentificationFailedForBadVersionID = 8989
	IdentificationFailedID              = 5778
	ClientKeyID                         = 982
	LoginQueueID                        = 2553
	CredentialsAcknowledgementID        = 5417
	SelectedServerDataExtendedID        = 900
	SelectedServerDataID                = 1568
	gameServerInformationID             = 920
	IdentificationSuccessID             = 7272
	HelloGameID                         = 5556
	RawDataID                           = 124
	CheckIntegrityID                    = 5541
	AuthenticationTicketID              = 3920
	AuthenticationTicketAcceptedID      = 8662
	BasicPongID                         = 8578
)
