// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 12:25:41.2101892 +0200 CEST m=+56.264234301

package messages

const (
	HelloConnectID                         = 1030
	IdentificationID                       = 2767
	VersionID                              = 9475
	SelectedServerDataExtendedID           = 900
	SelectedServerDataID                   = 1568
	GameServerInformationsID               = 920
	HelloGameID                            = 5556
	AuthenticationTicketID                 = 3920
	ItemID                                 = 10
	ItemWrapperID                          = 2
	ItemForPresetID                        = 5057
	CurrentMapID                           = 3437
	ChangeMapID                            = 6904
	MapInformationsRequestID               = 4598
	RawDataMessageID                       = 6253
	HouseInformationsID                    = 3662
	EntityDispositionInformationsID        = 2799
	GameContextActorPositionInformationsID = 8832
	EntityLookID                           = 9118
	SubEntityID                            = 3806
	GameContextActorInformationsID         = 3338
	GameRolePlayActorInformationsID        = 5720
	InteractiveElementID                   = 8429
	InteractiveElementSkillID              = 4345
)
