// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 22:03:00.8558877 +0200 CEST m=+0.597584801

package messages

import (
	"bytes"
	"fmt"
)

type ignoredGetList struct {
	PacketId uint32
}

var ignoredGetListMap = make(map[uint]*ignoredGetList)

func (ig *ignoredGetList) GetNOA(instance uint) Message {
	ignoredGetList_, ok := ignoredGetListMap[instance]

	if ok {
		return ignoredGetList_
	}

	ignoredGetListMap[instance] = &ignoredGetList{PacketId: IgnoredGetListID}
	return ignoredGetListMap[instance]
}

func (ig *ignoredGetList) Serialize(buff *bytes.Buffer) {
}

func (ig *ignoredGetList) Deserialize(reader *bytes.Reader) {
}

func (ig *ignoredGetList) GetPacketId() uint32 {
	return ig.PacketId
}

func (ig *ignoredGetList) String() string {
	return fmt.Sprintf("packetId: %d\n", ig.PacketId)
}
