// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 12:23:32.7229661 +0200 CEST m=+99.905406401

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type InteractiveElement struct {
	PacketId                 uint32
	elementId                int32
	elementTypeId            int32
	InteractiveElementSkill2 []*item
	InteractiveElementSkill3 []*item
	onCurrentMap             bool
}

var InteractiveElementMap = make(map[uint]*InteractiveElement)

func (In *InteractiveElement) GetNOA(instance uint) Message {
	InteractiveElement_, ok := InteractiveElementMap[instance]

	if ok {
		return InteractiveElement_
	}

	InteractiveElementMap[instance] = &InteractiveElement{PacketId: InteractiveElementID}
	return InteractiveElementMap[instance]
}

func (In *InteractiveElement) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, In.elementId)
	_ = binary.Write(buff, binary.BigEndian, In.elementTypeId)
	_ = binary.Write(buff, binary.BigEndian, uint16(len(In.InteractiveElementSkill2)))
	for i := 0; i < len(In.InteractiveElementSkill2); i++ {
		In.InteractiveElementSkill2[i].Serialize(buff)
	}
	_ = binary.Write(buff, binary.BigEndian, uint16(len(In.InteractiveElementSkill3)))
	for i := 0; i < len(In.InteractiveElementSkill3); i++ {
		In.InteractiveElementSkill3[i].Serialize(buff)
	}
	_ = binary.Write(buff, binary.BigEndian, In.onCurrentMap)
}

func (In *InteractiveElement) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &In.elementId)
	_ = binary.Read(reader, binary.BigEndian, &In.elementTypeId)
	var len2_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len2_)
	In.InteractiveElementSkill2 = nil
	for i := 0; i < int(len2_); i++ {
		aMessage2 := new(item)
		aMessage2.Deserialize(reader)
		In.InteractiveElementSkill2 = append(In.InteractiveElementSkill2, aMessage2)
	}
	var len3_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len3_)
	In.InteractiveElementSkill3 = nil
	for i := 0; i < int(len3_); i++ {
		aMessage3 := new(item)
		aMessage3.Deserialize(reader)
		In.InteractiveElementSkill3 = append(In.InteractiveElementSkill3, aMessage3)
	}
	_ = binary.Read(reader, binary.BigEndian, &In.onCurrentMap)
}

func (In *InteractiveElement) GetPacketId() uint32 {
	return In.PacketId
}

func (In *InteractiveElement) String() string {
	return fmt.Sprintf("packetId: %d\n", In.PacketId)
}
