// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 12:25:41.2276614 +0200 CEST m=+56.281706501

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type InteractiveElementSkill struct {
	PacketId         uint32
	skillId          int32
	skillInstanceUid int32
}

var InteractiveElementSkillMap = make(map[uint]*InteractiveElementSkill)

func (In *InteractiveElementSkill) GetNOA(instance uint) Message {
	InteractiveElementSkill_, ok := InteractiveElementSkillMap[instance]

	if ok {
		return InteractiveElementSkill_
	}

	InteractiveElementSkillMap[instance] = &InteractiveElementSkill{PacketId: InteractiveElementSkillID}
	return InteractiveElementSkillMap[instance]
}

func (In *InteractiveElementSkill) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt32(buff, In.skillId)
	_ = binary.Write(buff, binary.BigEndian, In.skillInstanceUid)
}

func (In *InteractiveElementSkill) Deserialize(reader *bytes.Reader) {
	In.skillId = utils.ReadVarInt32(reader)
	_ = binary.Read(reader, binary.BigEndian, &In.skillInstanceUid)
}

func (In *InteractiveElementSkill) GetPacketId() uint32 {
	return In.PacketId
}

func (In *InteractiveElementSkill) String() string {
	return fmt.Sprintf("packetId: %d\n", In.PacketId)
}
