// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 22:43:18.6054802 +0200 CEST m=+42.221228901

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type interactiveElementSkill struct {
	PacketId         uint32
	skillId          []int32
	skillInstanceUid int32
}

var interactiveElementSkillMap = make(map[uint]*interactiveElementSkill)

func GetInteractiveElementSkillNOA(instance uint) *interactiveElementSkill {
	interactiveElementSkill_, ok := interactiveElementSkillMap[instance]

	if ok {
		return interactiveElementSkill_
	}

	interactiveElementSkillMap[instance] = &interactiveElementSkill{PacketId: InteractiveElementSkillID}
	return interactiveElementSkillMap[instance]
}

func (in *interactiveElementSkill) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, uint16(len(in.skillId)))
	for i := 0; i < len(in.skillId); i++ {
		utils.WriteVarInt32(buff, in.skillId[i])
	}
	_ = binary.Write(buff, binary.BigEndian, in.skillInstanceUid)
}

func (in *interactiveElementSkill) Deserialize(reader *bytes.Reader) {
	var len0_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len0_)
	in.skillId = nil
	for i := 0; i < int(len0_); i++ {
		in.skillId = append(in.skillId, utils.ReadVarInt32(reader))
	}
	_ = binary.Read(reader, binary.BigEndian, &in.skillInstanceUid)
}

func (in *interactiveElementSkill) GetPacketId() uint32 {
	return in.PacketId
}

func (in *interactiveElementSkill) String() string {
	return fmt.Sprintf("packetId: %d\n", in.PacketId)
}
