// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 09:40:37.4483417 +0200 CEST m=+50.629504301

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type inventoryWeight struct {
	PacketId        uint32
	inventoryWeight int32
	shopWeight      int32
	weightMax       int32
}

var inventoryWeightMap = make(map[uint]*inventoryWeight)

func (in *inventoryWeight) GetNOA(instance uint) Message {
	inventoryWeight_, ok := inventoryWeightMap[instance]

	if ok {
		return inventoryWeight_
	}

	inventoryWeightMap[instance] = &inventoryWeight{PacketId: InventoryWeightID}
	return inventoryWeightMap[instance]
}

func (in *inventoryWeight) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt32(buff, in.inventoryWeight)
	utils.WriteVarInt32(buff, in.shopWeight)
	utils.WriteVarInt32(buff, in.weightMax)
}

func (in *inventoryWeight) Deserialize(reader *bytes.Reader) {
	in.inventoryWeight = utils.ReadVarInt32(reader)
	in.shopWeight = utils.ReadVarInt32(reader)
	in.weightMax = utils.ReadVarInt32(reader)
}

func (in *inventoryWeight) GetPacketId() uint32 {
	return in.PacketId
}

func (in *inventoryWeight) String() string {
	return fmt.Sprintf("packetId: %d\n", in.PacketId)
}
