// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 08:37:08.4872209 +0200 CEST m=+32.605901301

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type jobCrafterDirectorySettingsMessage struct {
	PacketId                    uint32
	jobCrafterDirectorySettings []*jobCrafterDirectorySettings
}

var jobCrafterDirectorySettingsMessageMap = make(map[uint]*jobCrafterDirectorySettingsMessage)

func GetJobCrafterDirectorySettingsMessageNOA(instance uint) *jobCrafterDirectorySettingsMessage {
	jobCrafterDirectorySettingsMessage_, ok := jobCrafterDirectorySettingsMessageMap[instance]

	if ok {
		return jobCrafterDirectorySettingsMessage_
	}

	jobCrafterDirectorySettingsMessageMap[instance] = &jobCrafterDirectorySettingsMessage{PacketId: JobCrafterDirectorySettingsMessageID}
	return jobCrafterDirectorySettingsMessageMap[instance]
}

func (jo *jobCrafterDirectorySettingsMessage) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, uint16(len(jo.jobCrafterDirectorySettings)))
	for i := 0; i < len(jo.jobCrafterDirectorySettings); i++ {
		jo.jobCrafterDirectorySettings[i].Serialize(buff)
	}
}

func (jo *jobCrafterDirectorySettingsMessage) Deserialize(reader *bytes.Reader) {
	var len0_ uint16
	_ = binary.Read(reader, binary.BigEndian, &len0_)
	jo.jobCrafterDirectorySettings = nil
	for i := 0; i < int(len0_); i++ {
		aMessage0 := new(jobCrafterDirectorySettings)
		aMessage0.Deserialize(reader)
		jo.jobCrafterDirectorySettings = append(jo.jobCrafterDirectorySettings, aMessage0)
	}
}

func (jo *jobCrafterDirectorySettingsMessage) GetPacketId() uint32 {
	return jo.PacketId
}

func (jo *jobCrafterDirectorySettingsMessage) String() string {
	return fmt.Sprintf("packetId: %d\n", jo.PacketId)
}
