// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 08:35:42.3650571 +0200 CEST m=+41.884368701

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type jobCrafterDirectorySettings struct {
	PacketId uint32
	jobId    byte
	minLevel byte
	free     bool
}

var jobCrafterDirectorySettingsMap = make(map[uint]*jobCrafterDirectorySettings)

func GetJobCrafterDirectorySettingsNOA(instance uint) *jobCrafterDirectorySettings {
	jobCrafterDirectorySettings_, ok := jobCrafterDirectorySettingsMap[instance]

	if ok {
		return jobCrafterDirectorySettings_
	}

	jobCrafterDirectorySettingsMap[instance] = &jobCrafterDirectorySettings{PacketId: JobCrafterDirectorySettingsID}
	return jobCrafterDirectorySettingsMap[instance]
}

func (jo *jobCrafterDirectorySettings) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, jo.jobId)
	_ = binary.Write(buff, binary.BigEndian, jo.minLevel)
	_ = binary.Write(buff, binary.BigEndian, jo.free)
}

func (jo *jobCrafterDirectorySettings) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &jo.jobId)
	_ = binary.Read(reader, binary.BigEndian, &jo.minLevel)
	_ = binary.Read(reader, binary.BigEndian, &jo.free)
}

func (jo *jobCrafterDirectorySettings) GetPacketId() uint32 {
	return jo.PacketId
}

func (jo *jobCrafterDirectorySettings) String() string {
	return fmt.Sprintf("packetId: %d\n", jo.PacketId)
}
