// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 09:38:15.4339125 +0200 CEST m=+0.020238201

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type objectEffect struct {
	PacketId uint32
	actionId int32
}

var objectEffectMap = make(map[uint]*objectEffect)

func GetObjectEffectNOA(instance uint) *objectEffect {
	objectEffect_, ok := objectEffectMap[instance]

	if ok {
		return objectEffect_
	}

	objectEffectMap[instance] = &objectEffect{PacketId: ObjectEffectID}
	return objectEffectMap[instance]
}

func (o *objectEffect) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt16(buff, o.actionId)
}

func (o *objectEffect) Deserialize(reader *bytes.Reader) {
	o.actionId = utils.ReadVarInt16(reader)
}

func (o *objectEffect) GetPacketId() uint32 {
	return o.PacketId
}

func (o *objectEffect) String() string {
	return fmt.Sprintf("packetId: %d\n", o.PacketId)
}
