// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 12:00:38.4457334 +0200 CEST m=+0.020215401

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type objectEffectString struct {
	PacketId uint32
	oE       *objectEffect
	value    []byte
}

var objectEffectStringMap = make(map[uint]*objectEffectString)

func GetObjectEffectStringNOA(instance uint) *objectEffectString {
	objectEffectString_, ok := objectEffectStringMap[instance]

	if ok {
		return objectEffectString_
	}

	objectEffectStringMap[instance] = &objectEffectString{PacketId: ObjectEffectStringID}
	return objectEffectStringMap[instance]
}

func (o *objectEffectString) Serialize(buff *bytes.Buffer) {
	o.oE.Serialize(buff)
	utils.WriteUTF(buff, o.value)
}

func (o *objectEffectString) Deserialize(reader *bytes.Reader) {
	o.oE = new(objectEffect)
	o.oE.Deserialize(reader)
	o.value = utils.ReadUTF(reader)
}

func (o *objectEffectString) GetPacketId() uint32 {
	return o.PacketId
}

func (o *objectEffectString) String() string {
	return fmt.Sprintf("packetId: %d\n", o.PacketId)
}
