// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 11:57:28.989315 +0200 CEST m=+0.019788801

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type objectEffectDuration struct {
	PacketId uint32
	oE       *objectEffect
	days     int32
	hours    byte
	minutes  byte
}

var objectEffectDurationMap = make(map[uint]*objectEffectDuration)

func GetObjectEffectDurationNOA(instance uint) *objectEffectDuration {
	objectEffectDuration_, ok := objectEffectDurationMap[instance]

	if ok {
		return objectEffectDuration_
	}

	objectEffectDurationMap[instance] = &objectEffectDuration{PacketId: ObjectEffectDurationID}
	return objectEffectDurationMap[instance]
}

func (o *objectEffectDuration) Serialize(buff *bytes.Buffer) {
	o.oE.Serialize(buff)
	utils.WriteVarInt16(buff, o.days)
	_ = binary.Write(buff, binary.BigEndian, o.hours)
	_ = binary.Write(buff, binary.BigEndian, o.minutes)
}

func (o *objectEffectDuration) Deserialize(reader *bytes.Reader) {
	o.oE = new(objectEffect)
	o.oE.Deserialize(reader)
	o.days = utils.ReadVarInt16(reader)
	_ = binary.Read(reader, binary.BigEndian, &o.hours)
	_ = binary.Read(reader, binary.BigEndian, &o.minutes)
}

func (o *objectEffectDuration) GetPacketId() uint32 {
	return o.PacketId
}

func (o *objectEffectDuration) String() string {
	return fmt.Sprintf("packetId: %d\n", o.PacketId)
}
