// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 15:42:28.5453969 +0200 CEST m=+11.878159201

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type objectItemInformationWithQuantity struct {
	PacketId uint32
	quantity int32
}

var objectItemInformationWithQuantityMap = make(map[uint]*objectItemInformationWithQuantity)

func (ob *objectItemInformationWithQuantity) GetNOA(instance uint) Message {
	objectItemInformationWithQuantity_, ok := objectItemInformationWithQuantityMap[instance]

	if ok {
		return objectItemInformationWithQuantity_
	}

	objectItemInformationWithQuantityMap[instance] = &objectItemInformationWithQuantity{PacketId: ObjectItemInformationWithQuantityID}
	return objectItemInformationWithQuantityMap[instance]
}

func (ob *objectItemInformationWithQuantity) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt32(buff, ob.quantity)
}

func (ob *objectItemInformationWithQuantity) Deserialize(reader *bytes.Reader) {
	ob.quantity = utils.ReadVarInt32(reader)
}

func (ob *objectItemInformationWithQuantity) GetPacketId() uint32 {
	return ob.PacketId
}

func (ob *objectItemInformationWithQuantity) String() string {
	return fmt.Sprintf("packetId: %d\n", ob.PacketId)
}
