// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 12:07:08.3413927 +0200 CEST m=+0.020440401

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type objectEffectDate struct {
	PacketId uint32
	oE       *objectEffect
	year     int32
	month    byte
	day      byte
	hour     byte
	minute   byte
}

var objectEffectDateMap = make(map[uint]*objectEffectDate)

func GetObjectEffectDateNOA(instance uint) *objectEffectDate {
	objectEffectDate_, ok := objectEffectDateMap[instance]

	if ok {
		return objectEffectDate_
	}

	objectEffectDateMap[instance] = &objectEffectDate{PacketId: ObjectEffectDateID}
	return objectEffectDateMap[instance]
}

func (o *objectEffectDate) Serialize(buff *bytes.Buffer) {
	o.oE.Serialize(buff)
	utils.WriteVarShort(buff, o.year)
	_ = binary.Write(buff, binary.BigEndian, o.month)
	_ = binary.Write(buff, binary.BigEndian, o.day)
	_ = binary.Write(buff, binary.BigEndian, o.hour)
	_ = binary.Write(buff, binary.BigEndian, o.minute)
}

func (o *objectEffectDate) Deserialize(reader *bytes.Reader) {
	o.oE = new(objectEffect)
	o.oE.Deserialize(reader)
	o.year = utils.ReadVarInt16(reader)
	_ = binary.Read(reader, binary.BigEndian, &o.month)
	_ = binary.Read(reader, binary.BigEndian, &o.day)
	_ = binary.Read(reader, binary.BigEndian, &o.hour)
	_ = binary.Read(reader, binary.BigEndian, &o.minute)
}

func (o *objectEffectDate) GetPacketId() uint32 {
	return o.PacketId
}

func (o *objectEffectDate) String() string {
	return fmt.Sprintf("packetId: %d\n", o.PacketId)
}
