// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 09:36:29.1396778 +0200 CEST m=+0.020380101

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type objectEffectInteger struct {
	PacketId uint32
	oE       *objectEffect
	value    int32
}

var objectEffectIntegerMap = make(map[uint]*objectEffectInteger)

func (o *objectEffectInteger) GetNOA(instance uint) Message {
	objectEffectInteger_, ok := objectEffectIntegerMap[instance]

	if ok {
		return objectEffectInteger_
	}

	objectEffectIntegerMap[instance] = &objectEffectInteger{PacketId: ObjectEffectIntegerID}
	return objectEffectIntegerMap[instance]
}

func (o *objectEffectInteger) Serialize(buff *bytes.Buffer) {
	o.oE.Serialize(buff)
	utils.WriteVarInt32(buff, o.value)
}

func (o *objectEffectInteger) Deserialize(reader *bytes.Reader) {
	o.oE = new(objectEffect)
	o.oE.Deserialize(reader)
	o.value = utils.ReadVarInt32(reader)
}

func (o *objectEffectInteger) GetPacketId() uint32 {
	return o.PacketId
}

func (o *objectEffectInteger) String() string {
	return fmt.Sprintf("packetId: %d\n", o.PacketId)
}
