// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 11:55:14.8308821 +0200 CEST m=+0.020737601

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type objectEffectMinMax struct {
	PacketId uint32
	oE       *objectEffect
	min      int32
	max      int32
}

var objectEffectMinMaxMap = make(map[uint]*objectEffectMinMax)

func (o *objectEffectMinMax) GetNOA(instance uint) Message {
	objectEffectMinMax_, ok := objectEffectMinMaxMap[instance]

	if ok {
		return objectEffectMinMax_
	}

	objectEffectMinMaxMap[instance] = &objectEffectMinMax{PacketId: ObjectEffectMinMaxID}
	return objectEffectMinMaxMap[instance]
}

func (o *objectEffectMinMax) Serialize(buff *bytes.Buffer) {
	o.oE.Serialize(buff)
	utils.WriteVarInt32(buff, o.min)
	utils.WriteVarInt32(buff, o.max)
}

func (o *objectEffectMinMax) Deserialize(reader *bytes.Reader) {
	o.oE = new(objectEffect)
	o.oE.Deserialize(reader)
	o.min = utils.ReadVarInt32(reader)
	o.max = utils.ReadVarInt32(reader)
}

func (o *objectEffectMinMax) GetPacketId() uint32 {
	return o.PacketId
}

func (o *objectEffectMinMax) String() string {
	return fmt.Sprintf("packetId: %d\n", o.PacketId)
}
