// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 12:02:48.877248 +0200 CEST m=+0.020110201

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type objectEffectDice struct {
	PacketId  uint32
	oE        *objectEffect
	diceNum   int32
	diceSide  int32
	diceConst int32
}

var objectEffectDiceMap = make(map[uint]*objectEffectDice)

func GetObjectEffectDiceNOA(instance uint) *objectEffectDice {
	objectEffectDice_, ok := objectEffectDiceMap[instance]

	if ok {
		return objectEffectDice_
	}

	objectEffectDiceMap[instance] = &objectEffectDice{PacketId: ObjectEffectDiceID}
	return objectEffectDiceMap[instance]
}

func (o *objectEffectDice) Serialize(buff *bytes.Buffer) {
	o.oE.Serialize(buff)
	utils.WriteVarInt32(buff, o.diceNum)
	utils.WriteVarInt32(buff, o.diceSide)
	utils.WriteVarInt32(buff, o.diceConst)
}

func (o *objectEffectDice) Deserialize(reader *bytes.Reader) {
	o.oE = new(objectEffect)
	o.oE.Deserialize(reader)
	o.diceNum = utils.ReadVarInt32(reader)
	o.diceSide = utils.ReadVarInt32(reader)
	o.diceConst = utils.ReadVarInt32(reader)
}

func (o *objectEffectDice) GetPacketId() uint32 {
	return o.PacketId
}

func (o *objectEffectDice) String() string {
	return fmt.Sprintf("packetId: %d\n", o.PacketId)
}
