// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 21:44:50.8827942 +0200 CEST m=+22.289245101

package messages

import (
	"bytes"
	"fmt"
)

type presets struct {
	PacketId    uint32
	itemWrapper *itemWrapper
}

var presetsMap = make(map[uint]*presets)

func (pr *presets) GetNOA(instance uint) Message {
	presets_, ok := presetsMap[instance]

	if ok {
		return presets_
	}

	presetsMap[instance] = &presets{PacketId: PresetsID}
	return presetsMap[instance]
}

func (pr *presets) Serialize(buff *bytes.Buffer) {
	pr.itemWrapper.Serialize(buff)
}

func (pr *presets) Deserialize(reader *bytes.Reader) {
	pr.itemWrapper = new(itemWrapper)
	pr.itemWrapper.Deserialize(reader)
}

func (pr *presets) GetPacketId() uint32 {
	return pr.PacketId
}

func (pr *presets) String() string {
	return fmt.Sprintf("packetId: %d\n", pr.PacketId)
}
