// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 21:52:00.6822278 +0200 CEST m=+36.159637601

package messages

import (
	"bytes"
	"fmt"
)

type presetsContainerPreset struct {
	PacketId    uint32
	preset      *preset
	itemWrapper *itemWrapper
}

var presetsContainerPresetMap = make(map[uint]*presetsContainerPreset)

func GetPresetsContainerPresetNOA(instance uint) *presetsContainerPreset {
	presetsContainerPreset_, ok := presetsContainerPresetMap[instance]

	if ok {
		return presetsContainerPreset_
	}

	presetsContainerPresetMap[instance] = &presetsContainerPreset{PacketId: PresetsContainerPresetID}
	return presetsContainerPresetMap[instance]
}

func (pr *presetsContainerPreset) Serialize(buff *bytes.Buffer) {
	pr.preset.Serialize(buff)
	pr.itemWrapper.Serialize(buff)
}

func (pr *presetsContainerPreset) Deserialize(reader *bytes.Reader) {
	pr.preset = new(preset)
	pr.preset.Deserialize(reader)
	pr.itemWrapper = new(itemWrapper)
	pr.itemWrapper.Deserialize(reader)
}

func (pr *presetsContainerPreset) GetPacketId() uint32 {
	return pr.PacketId
}

func (pr *presetsContainerPreset) String() string {
	return fmt.Sprintf("packetId: %d\n", pr.PacketId)
}
