// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 08:51:38.1403507 +0200 CEST m=+2.888607901

package messages

import (
	"bytes"
	"fmt"
)

type prismsList struct {
	PacketId    uint32
	itemWrapper *itemWrapper
}

var prismsListMap = make(map[uint]*prismsList)

func (pr *prismsList) GetNOA(instance uint) Message {
	prismsList_, ok := prismsListMap[instance]

	if ok {
		return prismsList_
	}

	prismsListMap[instance] = &prismsList{PacketId: PrismsListID}
	return prismsListMap[instance]
}

func (pr *prismsList) Serialize(buff *bytes.Buffer) {
	pr.itemWrapper.Serialize(buff)
}

func (pr *prismsList) Deserialize(reader *bytes.Reader) {
	pr.itemWrapper = new(itemWrapper)
	pr.itemWrapper.Deserialize(reader)
}

func (pr *prismsList) GetPacketId() uint32 {
	return pr.PacketId
}

func (pr *prismsList) String() string {
	return fmt.Sprintf("packetId: %d\n", pr.PacketId)
}
