// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 09:06:59.4029813 +0200 CEST m=+58.532444701

package messages

import (
	"GoDofus/utils"
	"bytes"
	"encoding/binary"
	"fmt"
)

type prismInformation struct {
	PacketId              uint32
	typeId                byte
	state                 byte
	nextVulnerabilityDate int32
	placementDate         int32
	rewardTokenCount      int32
}

var prismInformationMap = make(map[uint]*prismInformation)

func GetPrismInformationNOA(instance uint) *prismInformation {
	prismInformation_, ok := prismInformationMap[instance]

	if ok {
		return prismInformation_
	}

	prismInformationMap[instance] = &prismInformation{PacketId: PrismInformationID}
	return prismInformationMap[instance]
}

func (pr *prismInformation) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, pr.typeId)
	_ = binary.Write(buff, binary.BigEndian, pr.state)
	_ = binary.Write(buff, binary.BigEndian, pr.nextVulnerabilityDate)
	_ = binary.Write(buff, binary.BigEndian, pr.placementDate)
	utils.WriteVarInt32(buff, pr.rewardTokenCount)
}

func (pr *prismInformation) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &pr.typeId)
	_ = binary.Read(reader, binary.BigEndian, &pr.state)
	_ = binary.Read(reader, binary.BigEndian, &pr.nextVulnerabilityDate)
	_ = binary.Read(reader, binary.BigEndian, &pr.placementDate)
	pr.rewardTokenCount = utils.ReadVarInt32(reader)
}

func (pr *prismInformation) GetPacketId() uint32 {
	return pr.PacketId
}

func (pr *prismInformation) String() string {
	return fmt.Sprintf("packetId: %d\n", pr.PacketId)
}
