// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 09:02:57.5397117 +0200 CEST m=+48.106786101

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type prismGeolocalizedInformation struct {
	PacketId uint32
	worldX   uint16
	worldY   uint16
	mapId    float64
	item     *item
}

var prismGeolocalizedInformationMap = make(map[uint]*prismGeolocalizedInformation)

func (pr *prismGeolocalizedInformation) GetNOA(instance uint) Message {
	prismGeolocalizedInformation_, ok := prismGeolocalizedInformationMap[instance]

	if ok {
		return prismGeolocalizedInformation_
	}

	prismGeolocalizedInformationMap[instance] = &prismGeolocalizedInformation{PacketId: PrismGeolocalizedInformationID}
	return prismGeolocalizedInformationMap[instance]
}

func (pr *prismGeolocalizedInformation) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, pr.worldX)
	_ = binary.Write(buff, binary.BigEndian, pr.worldY)
	_ = binary.Write(buff, binary.BigEndian, pr.mapId)
	pr.item.Serialize(buff)
}

func (pr *prismGeolocalizedInformation) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &pr.worldX)
	_ = binary.Read(reader, binary.BigEndian, &pr.worldY)
	_ = binary.Read(reader, binary.BigEndian, &pr.mapId)
	pr.item = new(item)
	pr.item.Deserialize(reader)
}

func (pr *prismGeolocalizedInformation) GetPacketId() uint32 {
	return pr.PacketId
}

func (pr *prismGeolocalizedInformation) String() string {
	return fmt.Sprintf("packetId: %d\n", pr.PacketId)
}
