// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 21:50:03.2097692 +0200 CEST m=+64.861019801

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type prismGeolocalizedInformation struct {
	PacketId              uint32
	prismSubareaEmptyInfo *prismSubareaEmptyInfo
	worldX                int16
	worldY                int16
	mapId                 float64
	itemWrapper           *itemWrapper
}

var prismGeolocalizedInformationMap = make(map[uint]*prismGeolocalizedInformation)

func (pr *prismGeolocalizedInformation) GetNOA(instance uint) Message {
	prismGeolocalizedInformation_, ok := prismGeolocalizedInformationMap[instance]

	if ok {
		return prismGeolocalizedInformation_
	}

	prismGeolocalizedInformationMap[instance] = &prismGeolocalizedInformation{PacketId: PrismGeolocalizedInformationID}
	return prismGeolocalizedInformationMap[instance]
}

func (pr *prismGeolocalizedInformation) Serialize(buff *bytes.Buffer) {
	pr.prismSubareaEmptyInfo.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, pr.worldX)
	_ = binary.Write(buff, binary.BigEndian, pr.worldY)
	_ = binary.Write(buff, binary.BigEndian, pr.mapId)
	pr.itemWrapper.Serialize(buff)
}

func (pr *prismGeolocalizedInformation) Deserialize(reader *bytes.Reader) {
	pr.prismSubareaEmptyInfo = new(prismSubareaEmptyInfo)
	pr.prismSubareaEmptyInfo.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &pr.worldX)
	_ = binary.Read(reader, binary.BigEndian, &pr.worldY)
	_ = binary.Read(reader, binary.BigEndian, &pr.mapId)
	pr.itemWrapper = new(itemWrapper)
	pr.itemWrapper.Deserialize(reader)
}

func (pr *prismGeolocalizedInformation) GetPacketId() uint32 {
	return pr.PacketId
}

func (pr *prismGeolocalizedInformation) String() string {
	return fmt.Sprintf("packetId: %d\n", pr.PacketId)
}
