// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 22:26:48.4862223 +0200 CEST m=+0.761519001

package messages

import (
	"bytes"
	"fmt"
)

type questListRequest struct {
	PacketId uint32
}

var questListRequestMap = make(map[uint]*questListRequest)

func (qu *questListRequest) GetNOA(instance uint) Message {
	questListRequest_, ok := questListRequestMap[instance]

	if ok {
		return questListRequest_
	}

	questListRequestMap[instance] = &questListRequest{PacketId: QuestListRequestID}
	return questListRequestMap[instance]
}

func (qu *questListRequest) Serialize(buff *bytes.Buffer) {
}

func (qu *questListRequest) Deserialize(reader *bytes.Reader) {
}

func (qu *questListRequest) GetPacketId() uint32 {
	return qu.PacketId
}

func (qu *questListRequest) String() string {
	return fmt.Sprintf("packetId: %d\n", qu.PacketId)
}
