// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-03 17:47:43.007777 +0200 CEST m=+9.909648701

package messages

var Types_ = map[int]Message{
	ChangeMapID:                         &ChangeMap{},
	CurrentMapID:                        &CurrentMap{},
	HelloConnectID:                      &HelloConnect{},
	IdentificationID:                    &Identification{},
	MapInformationsRequestID:            &MapInformationsRequest{},
	RawDataMessageID:                    &RawDataMessage{},
	SelectedServerDataExtendedID:        &SelectedServerDataExtended{},
	AuthenticationTicketID:              &authenticationTicket{},
	GameServerInformationsID:            &gameServerInformations{},
	HelloGameID:                         &helloGame{},
	InventoryContentID:                  &inventoryContent{},
	InventoryWeightID:                   &inventoryWeight{},
	ItemID:                              &item{},
	ItemForPresetID:                     &itemForPreset{},
	ItemWrapperID:                       &itemWrapper{},
	ObjectEffectID:                      &objectEffect{},
	ObjectEffectCreatureID:              &objectEffectCreature{},
	ObjectEffectDateID:                  &objectEffectDate{},
	ObjectEffectDiceID:                  &objectEffectDice{},
	ObjectEffectDurationID:              &objectEffectDuration{},
	ObjectEffectIntegerID:               &objectEffectInteger{},
	ObjectEffectLadderID:                &objectEffectLadder{},
	ObjectEffectMinMaxID:                &objectEffectMinMax{},
	ObjectEffectMountID:                 &objectEffectMount{},
	ObjectEffectStringID:                &objectEffectString{},
	ObjectItemID:                        &objectItem{},
	ObjectItemInformationWithQuantityID: &objectItemInformationWithQuantity{},
	SelectedServerDataID:                &selectedServerData{},
	VersionID:                           &version{},
}
