// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 12:16:45.4134677 +0200 CEST m=+29.307462901

package messages

var Types_ = map[int]Message{
	ChangeMapID:                            &ChangeMap{},
	CurrentMapID:                           &CurrentMap{},
	EntityDispositionInformationsID:        &EntityDispositionInformations{},
	EntityLookID:                           &EntityLook{},
	GameContextActorInformationsID:         &GameContextActorInformations{},
	GameContextActorPositionInformationsID: &GameContextActorPositionInformations{},
	GameRolePlayActorInformationsID:        &GameRolePlayActorInformations{},
	HelloConnectID:                         &HelloConnect{},
	HouseInformationsID:                    &HouseInformations{},
	IdentificationID:                       &Identification{},
	MapInformationsRequestID:               &MapInformationsRequest{},
	RawDataMessageID:                       &RawDataMessage{},
	SelectedServerDataExtendedID:           &SelectedServerDataExtended{},
	SubEntityID:                            &SubEntity{},
	AuthenticationTicketID:                 &authenticationTicket{},
	GameServerInformationsID:               &gameServerInformations{},
	HelloGameID:                            &helloGame{},
	ItemID:                                 &item{},
	ItemForPresetID:                        &itemForPreset{},
	ItemWrapperID:                          &itemWrapper{},
	SelectedServerDataID:                   &selectedServerData{},
	VersionID:                              &version{},
}
