// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-09-11 12:39:55.2435655 +0200 CEST m=+32.919127901

package messages

var Types_ = map[int]Message{
	AbstractFightTeamInformationsID:        &AbstractFightTeamInformations{},
	ChangeMapID:                            &ChangeMap{},
	CurrentMapID:                           &CurrentMap{},
	EntityDispositionInformationsID:        &EntityDispositionInformations{},
	EntityLookID:                           &EntityLook{},
	FightOptionsInformationsID:             &FightOptionsInformations{},
	FightTeamInformationsID:                &FightTeamInformations{},
	FightTeamMemberInformationsID:          &FightTeamMemberInformations{},
	GameContextActorInformationsID:         &GameContextActorInformations{},
	GameContextActorPositionInformationsID: &GameContextActorPositionInformations{},
	GameRolePlayActorInformationsID:        &GameRolePlayActorInformations{},
	HelloConnectID:                         &HelloConnect{},
	HouseInformationsID:                    &HouseInformations{},
	IdentificationID:                       &Identification{},
	InteractiveElementID:                   &InteractiveElement{},
	InteractiveElementSkillID:              &InteractiveElementSkill{},
	MapInformationsRequestID:               &MapInformationsRequest{},
	MapObstacleID:                          &MapObstacle{},
	RawDataMessageID:                       &RawDataMessage{},
	SelectedServerDataExtendedID:           &SelectedServerDataExtended{},
	StatedElementID:                        &StatedElement{},
	SubEntityID:                            &SubEntity{},
	AuthenticationTicketID:                 &authenticationTicket{},
	GameServerInformationsID:               &gameServerInformations{},
	HelloGameID:                            &helloGame{},
	ItemID:                                 &item{},
	ItemForPresetID:                        &itemForPreset{},
	ItemWrapperID:                          &itemWrapper{},
	SelectedServerDataID:                   &selectedServerData{},
	VersionID:                              &version{},
}
