// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-25 10:18:45.7099917 +0200 CEST m=+0.003729801

package messages

import (
	"bytes"
	"fmt"
)

type selectedServerDataExtended struct {
	PacketId uint32
	sSD      *selectedServerData
	gSI      []*gameServerInformations
}

var selectedServerDataExtended_ = &selectedServerDataExtended{PacketId: SelectedServerDataExtendedID}

func GetSelectedServerDataExtendedNOA() *selectedServerDataExtended {
	return selectedServerDataExtended_
}

func (s *selectedServerDataExtended) Serialize(buff *bytes.Buffer) {

}

func (s *selectedServerDataExtended) Deserialize(reader *bytes.Reader) {
	s.sSD = new(selectedServerData)
	s.sSD.Deserialize(reader)

	var serverLen uint16
	for i := uint16(0); i < serverLen; i++ {
		var gSI = new(gameServerInformations)
		gSI.Deserialize(reader)
		s.gSI = append(s.gSI, gSI)
	}
}

func (s *selectedServerDataExtended) GetPacketId() uint32 {
	return s.PacketId
}

func (s *selectedServerDataExtended) String(reader *bytes.Reader) string {
	return fmt.Sprintf("PacketId: %d\n", s.PacketId)
}
