// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 14:33:20.1876801 +0200 CEST m=+7.148824201

package messages

import (
	"bytes"
	"fmt"
)

type sequenceNumberRequest struct {
	PacketId uint32
}

var sequenceNumberRequestMap = make(map[uint]*sequenceNumberRequest)

func GetSequenceNumberRequestNOA(instance uint) *sequenceNumberRequest {
	sequenceNumberRequest_, ok := sequenceNumberRequestMap[instance]

	if ok {
		return sequenceNumberRequest_
	}

	sequenceNumberRequestMap[instance] = &sequenceNumberRequest{PacketId: SequenceNumberRequestID}
	return sequenceNumberRequestMap[instance]
}

func (se *sequenceNumberRequest) Serialize(buff *bytes.Buffer) {
}

func (se *sequenceNumberRequest) Deserialize(reader *bytes.Reader) {
}

func (se *sequenceNumberRequest) GetPacketId() uint32 {
	return se.PacketId
}

func (se *sequenceNumberRequest) String() string {
	return fmt.Sprintf("packetId: %d\n", se.PacketId)
}
