// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-28 19:03:11.2190239 +0200 CEST m=+0.020871301

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type serverSessionConstant struct {
	PacketId uint32
	id       int32
}

var serverSessionConstantMap = make(map[uint]*serverSessionConstant)

func GetServerSessionConstantNOA(instance uint) *serverSessionConstant {
	serverSessionConstant_, ok := serverSessionConstantMap[instance]

	if ok {
		return serverSessionConstant_
	}

	serverSessionConstantMap[instance] = &serverSessionConstant{PacketId: ServerSessionConstantID}
	return serverSessionConstantMap[instance]
}

func (s *serverSessionConstant) Serialize(buff *bytes.Buffer) {
	utils.WriteVarShort(buff, s.id)
}

func (s *serverSessionConstant) Deserialize(reader *bytes.Reader) {
	s.id = utils.ReadVarInt16(reader)
}

func (s *serverSessionConstant) GetPacketId() uint32 {
	return s.PacketId
}

func (s *serverSessionConstant) String() string {
	return fmt.Sprintf("packetId: %d\n", s.PacketId)
}
