// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-28 19:05:20.5912587 +0200 CEST m=+0.021120701

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type serverSessionConstantString struct {
	PacketId uint32
	ssC      *serverSessionConstant
	value    []byte
}

var serverSessionConstantStringMap = make(map[uint]*serverSessionConstantString)

func GetServerSessionConstantStringNOA(instance uint) *serverSessionConstantString {
	serverSessionConstantString_, ok := serverSessionConstantStringMap[instance]

	if ok {
		return serverSessionConstantString_
	}

	serverSessionConstantStringMap[instance] = &serverSessionConstantString{PacketId: ServerSessionConstantStringID}
	return serverSessionConstantStringMap[instance]
}

func (s *serverSessionConstantString) Serialize(buff *bytes.Buffer) {
	s.ssC.Serialize(buff)
	utils.WriteUTF(buff, s.value)
}

func (s *serverSessionConstantString) Deserialize(reader *bytes.Reader) {
	s.ssC = new(serverSessionConstant)
	s.ssC.Deserialize(reader)
	s.value = utils.ReadUTF(reader)
}

func (s *serverSessionConstantString) GetPacketId() uint32 {
	return s.PacketId
}

func (s *serverSessionConstantString) String() string {
	return fmt.Sprintf("packetId: %d\n", s.PacketId)
}
