// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 10:27:05.1266875 +0200 CEST m=+0.020582101

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type shortcutObjectPreset struct {
	PacketId uint32
	sO       *shortcutObject
	presetId uint16
}

var shortcutObjectPresetMap = make(map[uint]*shortcutObjectPreset)

func GetShortcutObjectPresetNOA(instance uint) *shortcutObjectPreset {
	shortcutObjectPreset_, ok := shortcutObjectPresetMap[instance]

	if ok {
		return shortcutObjectPreset_
	}

	shortcutObjectPresetMap[instance] = &shortcutObjectPreset{PacketId: ShortcutObjectPresetID}
	return shortcutObjectPresetMap[instance]
}

func (s *shortcutObjectPreset) Serialize(buff *bytes.Buffer) {
	s.sO.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, s.presetId)
}

func (s *shortcutObjectPreset) Deserialize(reader *bytes.Reader) {
	s.sO = new(shortcutObject)
	s.sO.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &s.presetId)
}

func (s *shortcutObjectPreset) GetPacketId() uint32 {
	return s.PacketId
}

func (s *shortcutObjectPreset) String() string {
	return fmt.Sprintf("packetId: %d\n", s.PacketId)
}
