// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 10:33:26.4219947 +0200 CEST m=+0.020437401

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type shortcutSpell struct {
	PacketId uint32
	sO       *shortcut
	spellId  int32
}

var shortcutSpellMap = make(map[uint]*shortcutSpell)

func GetShortcutSpellNOA(instance uint) *shortcutSpell {
	shortcutSpell_, ok := shortcutSpellMap[instance]

	if ok {
		return shortcutSpell_
	}

	shortcutSpellMap[instance] = &shortcutSpell{PacketId: ShortcutSpellID}
	return shortcutSpellMap[instance]
}

func (s *shortcutSpell) Serialize(buff *bytes.Buffer) {
	s.sO.Serialize(buff)
	utils.WriteVarInt16(buff, s.spellId)
}

func (s *shortcutSpell) Deserialize(reader *bytes.Reader) {
	s.sO = new(shortcut)
	s.sO.Deserialize(reader)
	s.spellId = utils.ReadVarInt16(reader)
}

func (s *shortcutSpell) GetPacketId() uint32 {
	return s.PacketId
}

func (s *shortcutSpell) String() string {
	return fmt.Sprintf("packetId: %d\n", s.PacketId)
}
