// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 10:28:58.1723978 +0200 CEST m=+0.019895801

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type shortcutObjectIdolsPreset struct {
	PacketId uint32
	sO       *shortcutObject
	presetId uint16
}

var shortcutObjectIdolsPresetMap = make(map[uint]*shortcutObjectIdolsPreset)

func (s *shortcutObjectIdolsPreset) GetNOA(instance uint) Message {
	shortcutObjectIdolsPreset_, ok := shortcutObjectIdolsPresetMap[instance]

	if ok {
		return shortcutObjectIdolsPreset_
	}

	shortcutObjectIdolsPresetMap[instance] = &shortcutObjectIdolsPreset{PacketId: ShortcutObjectIdolsPresetID}
	return shortcutObjectIdolsPresetMap[instance]
}

func (s *shortcutObjectIdolsPreset) Serialize(buff *bytes.Buffer) {
	s.sO.Serialize(buff)
	_ = binary.Write(buff, binary.BigEndian, s.presetId)
}

func (s *shortcutObjectIdolsPreset) Deserialize(reader *bytes.Reader) {
	s.sO = new(shortcutObject)
	s.sO.Deserialize(reader)
	_ = binary.Read(reader, binary.BigEndian, &s.presetId)
}

func (s *shortcutObjectIdolsPreset) GetPacketId() uint32 {
	return s.PacketId
}

func (s *shortcutObjectIdolsPreset) String() string {
	return fmt.Sprintf("packetId: %d\n", s.PacketId)
}
