// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 10:13:11.143799 +0200 CEST m=+0.020312701

package messages

import (
	"bytes"
	"encoding/binary"
	"fmt"
)

type shortcutBarContent struct {
	PacketId uint32
	barType  byte
	iW       *itemWrapper
}

var shortcutBarContentMap = make(map[uint]*shortcutBarContent)

func GetShortcutBarContentNOA(instance uint) *shortcutBarContent {
	shortcutBarContent_, ok := shortcutBarContentMap[instance]

	if ok {
		return shortcutBarContent_
	}

	shortcutBarContentMap[instance] = &shortcutBarContent{PacketId: ShortcutBarContentID}
	return shortcutBarContentMap[instance]
}

func (s *shortcutBarContent) Serialize(buff *bytes.Buffer) {
	_ = binary.Write(buff, binary.BigEndian, s.barType)
	s.iW.Serialize(buff)
}

func (s *shortcutBarContent) Deserialize(reader *bytes.Reader) {
	_ = binary.Read(reader, binary.BigEndian, &s.barType)
	s.iW = new(itemWrapper)
	s.iW.Deserialize(reader)
}

func (s *shortcutBarContent) GetPacketId() uint32 {
	return s.PacketId
}

func (s *shortcutBarContent) String() string {
	return fmt.Sprintf("packetId: %d\n", s.PacketId)
}
