// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 10:24:53.5096093 +0200 CEST m=+0.020496301

package messages

import (
	"bytes"
	"fmt"
)

type shortcutObject struct {
	PacketId uint32
	s        *shortcut
}

var shortcutObjectMap = make(map[uint]*shortcutObject)

func (s *shortcutObject) GetNOA(instance uint) Message {
	shortcutObject_, ok := shortcutObjectMap[instance]

	if ok {
		return shortcutObject_
	}

	shortcutObjectMap[instance] = &shortcutObject{PacketId: ShortcutObjectID}
	return shortcutObjectMap[instance]
}

func (s *shortcutObject) Serialize(buff *bytes.Buffer) {
	s.s.Serialize(buff)
}

func (s *shortcutObject) Deserialize(reader *bytes.Reader) {
	s.s = new(shortcut)
	s.s.Deserialize(reader)
}

func (s *shortcutObject) GetPacketId() uint32 {
	return s.PacketId
}

func (s *shortcutObject) String() string {
	return fmt.Sprintf("packetId: %d\n", s.PacketId)
}
