// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 22:47:51.7341332 +0200 CEST m=+30.054234301

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type skillActionDescription struct {
	PacketId uint32
	skillId  int32
}

var skillActionDescriptionMap = make(map[uint]*skillActionDescription)

func GetSkillActionDescriptionNOA(instance uint) *skillActionDescription {
	skillActionDescription_, ok := skillActionDescriptionMap[instance]

	if ok {
		return skillActionDescription_
	}

	skillActionDescriptionMap[instance] = &skillActionDescription{PacketId: SkillActionDescriptionID}
	return skillActionDescriptionMap[instance]
}

func (sk *skillActionDescription) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt16(buff, sk.skillId)
}

func (sk *skillActionDescription) Deserialize(reader *bytes.Reader) {
	sk.skillId = utils.ReadVarInt16(reader)
}

func (sk *skillActionDescription) GetPacketId() uint32 {
	return sk.PacketId
}

func (sk *skillActionDescription) String() string {
	return fmt.Sprintf("packetId: %d\n", sk.PacketId)
}
