// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-29 22:51:52.5572164 +0200 CEST m=+40.512912901

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type skillActionDescriptionCollect struct {
	PacketId                    uint32
	skillActionDescriptionTimed *skillActionDescriptionTimed
	min                         int32
	max                         int32
}

var skillActionDescriptionCollectMap = make(map[uint]*skillActionDescriptionCollect)

func (sk *skillActionDescriptionCollect) GetNOA(instance uint) Message {
	skillActionDescriptionCollect_, ok := skillActionDescriptionCollectMap[instance]

	if ok {
		return skillActionDescriptionCollect_
	}

	skillActionDescriptionCollectMap[instance] = &skillActionDescriptionCollect{PacketId: SkillActionDescriptionCollectID}
	return skillActionDescriptionCollectMap[instance]
}

func (sk *skillActionDescriptionCollect) Serialize(buff *bytes.Buffer) {
	sk.skillActionDescriptionTimed.Serialize(buff)
	utils.WriteVarInt16(buff, sk.min)
	utils.WriteVarInt16(buff, sk.max)
}

func (sk *skillActionDescriptionCollect) Deserialize(reader *bytes.Reader) {
	sk.skillActionDescriptionTimed = new(skillActionDescriptionTimed)
	sk.skillActionDescriptionTimed.Deserialize(reader)
	sk.min = utils.ReadVarInt16(reader)
	sk.max = utils.ReadVarInt16(reader)
}

func (sk *skillActionDescriptionCollect) GetPacketId() uint32 {
	return sk.PacketId
}

func (sk *skillActionDescriptionCollect) String() string {
	return fmt.Sprintf("packetId: %d\n", sk.PacketId)
}
