// Code generated by go GenerateMessage; DO NOT EDIT.
// This file was generated by robots at
// 2021-08-30 15:39:22.0723255 +0200 CEST m=+46.212813701

package messages

import (
	"GoDofus/utils"
	"bytes"
	"fmt"
)

type storageKamasUpdate struct {
	PacketId   uint32
	kamasTotal float64
}

var storageKamasUpdateMap = make(map[uint]*storageKamasUpdate)

func GetStorageKamasUpdateNOA(instance uint) *storageKamasUpdate {
	storageKamasUpdate_, ok := storageKamasUpdateMap[instance]

	if ok {
		return storageKamasUpdate_
	}

	storageKamasUpdateMap[instance] = &storageKamasUpdate{PacketId: StorageKamasUpdateID}
	return storageKamasUpdateMap[instance]
}

func (st *storageKamasUpdate) Serialize(buff *bytes.Buffer) {
	utils.WriteVarInt64(buff, st.kamasTotal)
}

func (st *storageKamasUpdate) Deserialize(reader *bytes.Reader) {
	st.kamasTotal = float64(utils.ReadVarInt64(reader))
}

func (st *storageKamasUpdate) GetPacketId() uint32 {
	return st.PacketId
}

func (st *storageKamasUpdate) String() string {
	return fmt.Sprintf("packetId: %d\n", st.PacketId)
}
